---
title: "International moves are increasingly made as a couple"
author: "Duc-Quang Nguyen"
date: "2025-05-10"
output: html_document
---

```{r setup & load data, include=FALSE}
source("_helpers.R")
run_n_check <- T
```


```{r load}
# gender
c2t_A1 <- read_csv(here("Data", "code2txt", "NCCR MMS Codes A1.csv"))
# pays 
c2t_B1 <- read_csv(here("Data", "code2txt", "NCCR_MMS_codes - B1.csv"))

b102f <- tibble(
  B10 = c(1, 2, 3, 4, 5),
  b10 = c("Partner already in Switzerland", 
          "Moved together",  
          "Partner moved before",
          "Partner moved after", 
          "Partner has not moved yet")
  )
b102f %<>% 
  mutate(
    b10 = factor(b10, levels = b102f$b10[c(2,1, 3, 4, 5)]) #b102f$b10[c(2,1, 3, 4, 5)])
  )

data_all <- mms_df  %>% 
  left_join(c2t_A1) %>% 
  left_join(c2t_B1) %>% 
  mutate(
    migy = mms_encode_migration_year(A6,year)
  ) %>% 
  left_join(
    migy2yearIntervals) %>% 
  mutate(
    mar = case_when(
      B9 == 1 ~ T,
      B9 == 2 ~ F,
      T ~ NA
    )) %>% 
  left_join(
    b102f, by = "B10"
  )

f_df <- data_all %>% 
  select(year:b10)
  
```


```{r wrangle & check}
coum2y_df <- f_df %>% 
  filter(!is.na(mig_2y)) %>% 
  filter(!is.na(mar)) %>% 
  group_by(mig_2y, mar) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = T),
  ) %>% 
  group_by(mig_2y) %>% 
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100, 
  ) %>% 
  ungroup()

coum4y_df <- f_df %>% 
  filter(!is.na(mig_4y)) %>% 
  filter(!is.na(mar)) %>% 
  group_by(mig_4y, mar) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = T),
  ) %>% 
  group_by(mig_4y) %>% 
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100, 
  ) %>% 
  ungroup()


if(run_n_check) {
  coum2y_df %>% 
    select(mig_2y, n_y, mar, share) %>%
    pivot_wider(
      names_from = mar,
      values_from = share
    ) 
  
  coum4y_df %>% 
    select(mig_4y, n_y, mar, share) %>%
    pivot_wider(
      names_from = mar,
      values_from = share
    ) 
}

coum_p_df <- f_df %>% 
  filter(year == 2024) %>% 
  filter(!is.na(country)) %>% 
  filter(!is.na(mar)) %>% 
  group_by(country, mar) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = T),
  ) %>% 
  group_by(country) %>% 
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100, 
  ) %>% 
  ungroup()
  
if(run_n_check) {
  coum_p_df %>% 
    select(country, n_y, mar, share) %>%
    pivot_wider(
      names_from = mar,
      values_from = share
    ) 
}

cou_ms_df <- f_df %>% 
  filter(year == 2024) %>% 
  filter(!is.na(b10)) %>% 
  filter(!is.na(mig_4y)) %>% 
  group_by(mig_4y, b10) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = T),
  ) %>% 
  group_by(mig_4y) %>% 
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100, 
  ) %>% 
  ungroup()

cou_msa_df <- f_df %>% 
  filter(year == 2024) %>% 
  filter(!is.na(b10)) %>% 
  group_by(b10) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = T),
  ) %>% 
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = round(weight/sum(weight, na.rm = TRUE)*100, 0)
  ) %>% 
  ungroup() %>% 
  arrange(b10)
  

if(run_n_check) {
  cou_ms_df %>% 
    select(mig_4y, n_y, b10, share) %>%
    pivot_wider(
      names_from = b10,
      values_from = share
    )  
  cou_msa_df
}


```



### VIZ

#### 1. main  chart

```{r 1}

annot_df <- tibble(
  mig_4y = rep(3, 2),
  value = c(40, 88),
  txt = c("In a relationship", "Alone")
)


p_coum_1 <- coum4y_df %>% 
  ggplot(aes(x = mig_4y, y = share, group = mar)) +
  geom_area(aes(fill = mar), alpha = 1, show.legend = FALSE) + 
  geom_line(data = coum4y_df %>% filter(mar == T),
             color = "white", linewidth = 1
  ) +
  theme_mms(
    grid="XY", axis="xy", 
    grid_col =  scales::alpha("lightgrey", 0.6),
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 3),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 2)
  ) +
  theme(
    panel.background = element_rect(fill = NA),  # transparent
    panel.ontop = TRUE
  ) +
   # remove any scale expansion
  scale_x_discrete(expand = c(0,0), name = "") +
  # have y scale not start at 0, add unit % 
  scale_y_continuous(expand = c(0,0), name = "", 
                     breaks = seq(25, 100, 25),
                     labels = function(x) paste0(x, "%")) +
  scale_fill_manual(values = nccr_colors_1[c(2, 7)]) +
  scale_size_continuous(guide = guide_legend(), 
                        breaks = scales::breaks_pretty(n = 4)) + # choose ~3 "pretty" breaks
  labs(
    title = "Recent migrants more often arrived as part of a couple than those in the early 2000s",
    subtitle = "Share of migrants in a relationship at time of arrival, by migration period"
  ) +
  geom_richtext(
    data = annot_df, 
    aes(x = mig_4y, y = value, label = txt, group = 1),
    fill = NA, label.color = NA,# remove background and outline,
    color = "white", size = 6,# fontface = "bold",
    hjust = 0.5, family = mms_base_family
  )

  
 p_coum_1 
```

#### 2. Stacked bar  

```{r 2}

coum_p_ordered <- coum_p_df %>%
  filter(country != "Other countries") %>%
  filter(mar == T) %>%
  mutate(
    country = factor(country) %>% fct_reorder(share, .desc = T)
  ) %>%
  arrange(country) %>%
  pull(country) # .$country %>% as.character()

# On prépare le dataframe pour le plot
plot_data <- coum_p_df %>%
  filter(country != "Other countries") %>%
  mutate(
    # On applique l'ordre des pays (inversé pour l'axe Y de ggplot)
    country = factor(country, levels = rev(coum_p_ordered)),
    
    # On définit l'ordre de stacking : T (en couple) à gauche, F (seul) à droite
    mar = factor(mar, levels = c(T, F))
  ) %>% 
  arrange(mar)


# --- 2. Le Graphique de Base (geom_col) ---

p_coum_2 <- plot_data %>%
  # aes() principal : x=share, y=country, fill=mar
  ggplot(aes(x = share, y = country, fill = rev(mar))) +
  
  # On remplace geom_rect par geom_col !
  geom_col(
    colour = "white",
    linewidth = bar_width, 
    alpha = 1
  ) +
  
  # --- Thèmes et Échelles (presque identiques) ---
  theme_mms(
    grid = F, axis = F,
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 2),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 3)
  ) +
  theme(
    legend.position = "none",
    # On cache les labels de l'axe Y (on les ajoutera manuellement)
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  ) +
  
  # On utilise juste scale_fill_manual.
  # L'ordre c(2, 13) correspond aux niveaux c(T, F)
  scale_fill_manual(values = nccr_colors_1[c(2,7)]) + 
  
  # Axe X (inchangé, mais on pourrait le réactiver si besoin)
  scale_x_continuous(
    name = "", expand = c(0, 0), position = "top",
    breaks = NULL
  ) +
  # Axe Y (maintenant discret)
  scale_y_discrete(name = "", labels = NULL, expand = c(0, 0))

# --- 3. Préparation des Labels (logique originale) ---

# Labels des NOMS de pays (simplifié)
coum_p_labels_simple <- plot_data %>%
  distinct(country) %>% # On a juste besoin de la liste des pays
  mutate(
    labels = gsub(" ", "<br>", country)
  )

# Labels des VALEURS (recréation de ta logique xmin/xmax/hjust)
coum_value_labels_simple <- plot_data %>%
  # S'assurer de l'ordre de calcul (T, puis F)
  arrange(country, mar) %>% 
  group_by(country) %>%
  mutate(
    # On calcule la position cumulative
    xmax = cumsum(share),
    xmin = xmax - share
  ) %>%
  ungroup() %>%
  mutate(
    # On applique la logique de position de ton code original :
    x_pos = ifelse(mar == T, xmax, xmin),
    hjust_val = ifelse(mar == T, 1.05, -0.05), # 1.05 = droite, -0.05 = gauche
    label_val = paste0(round(share, num_n_dect), "")
  )

# --- 4. Assemblage Final ---
p_coum_2a <- p_coum_2 +
  # --- Labels des Pays ---
  # On les place en haut à gauche de la barre (vjust=1, hjust=0)
  geom_richtext(
    data = coum_p_labels_simple,
    aes(
      x = 0.5, # Près de 0
      y = country, 
      label = labels
    ),
    fill = NA, label.color = NA,
    size = 4,
    hjust = 0,     # Aligner à gauche
    nudge_x = 0.5, # (Garde ton nudge original)
    nudge_y = 0.4,
    vjust = 1,     # Aligner en HAUT
    colour = "white",
    family = mms_base_family
  ) +
  
  # --- Labels des Valeurs (Pourcentages) ---
  geom_richtext(
    data = coum_value_labels_simple,
    aes(
      x = x_pos, 
      y = country, 
      label = label_val, 
      hjust = hjust_val
    ),
    fill = NA, label.color = NA,
    vjust = 1, # Aligner en BAS
    nudge_y = -0.15, # (Garde ton nudge original)
    size = 3.5, 
    alpha = 1, 
    colour = "white",
    family = mms_base_family
  ) +
  annotate("text", x = 0, y = nlevels(plot_data$country)+0.2,
           label = "In a relationship", vjust = -3, hjust = 0, 
           size = 3.5,
           family = mms_base_family, fontface = "bold",
           color = nccr_colors_1[7]) +
  annotate("text", x = 100, y = nlevels(plot_data$country)+0.2,
           label = "Alone", vjust = -3, hjust = 1, 
           size = 3.5,
           family = mms_base_family, fontface = "bold",
           color = nccr_colors_1[3]) +
  coord_cartesian(clip = "off") + # Pour que l'annotation ne soit pas coupée
  labs(
    title = str_c(
      "Those from neighboring countries more often migrate alone"
     # '<span style="color:', nccr_categorical()[14], ';">alone</span>'
    ),
    subtitle = str_c("Share of migrants in a relationship at time of migration, ",
                     "by country of origin in 2024")
  )

# Afficher le graphique
p_coum_2a


```

#### 3. waffle

```{r 3}

colw <- c("#58582C", nccr_colors_1[c(8,6,5)], "#C3C09F")

cou_msa_df %<>% 
  mutate(
    x = c(5.5, 5.3, 5.2, 5.2, 7),
    y = c(2,5, 7, 9, 10),
    hjust = c(0.5, 0.5, 0.5, 0.5, 0.5),
    color = colw,
    label = str_c(
      " <span style='color:",  color ,";'>",
      b10, "</span>: <span style='color:black;font-size:14px;'>", round(share, num_n_dect), "</span>"),
  )

p_coum_3 <- cou_msa_df %>% 
  ggplot() +
  geom_waffle(
    aes(fill = b10, values = share),
    n_rows = 10,
    size = 0.9, 
    colour = "white",
    flip = TRUE
  ) +
  theme_mms(
    grid=FALSE, axis=F, 
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 2),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 1)
   # grid_col = "black",
  ) + 
  theme(
    legend.text = element_markdown(size = 12),  # Enables HTML/Markdown in legend labels
    legend.position = "top",
    legend.justification = c(0, 1), 
    axis.text.y = element_blank(),  # Hide y-axis text
    axis.ticks.y = element_blank() , # Hide y-axis ticks
    axis.text.x = element_blank(),  # Hide y-axis text
    axis.ticks.x = element_blank() , # Hide y-axis ticks
  ) +
  scale_fill_manual(
    values = colw,
    labels = cou_msa_df$label)  +
  #scale_color_manual(values = nccr_bi_colors[c(13,10,1,1,1,1)])  +
  labs(
    title = str_c("Migrating as a couple: only 1 in 3 move together"),
      # "Migrating as a couple: only 1 in 3",
      # '<span style="color:', nccr_colors_1[8], ';"> move together</span>'),
    subtitle = "Out of 100 couples, status at the time of migration in 2024"
  ) + 
  guides(fill = guide_legend(ncol = 1, title ="")) +
  # geom_richtext(
  #   aes(x = x, y = y, label = label, hjust = hjust, fill = b10),
  #   #fill = nccr_bi_colors[13], 
  #   #label.color = NA,# remove background and outline,
  #   size = 4, 
  #   colour = "white",
  #   family = mms_base_family,
  #   alpha = 1
  # ) +
  # scale_color_identity() +
  scale_x_continuous(name = "", expand = c(0,0)) +
  scale_y_continuous(name = "", expand = c(0,0))

p_coum_3
```

#### patch

```{r patch}
patchwork <- (p_coum_1 / p_coum_3) + 
  plot_layout(heights = c(1, 1)) | 
  p_coum_2a 

patchwork


mms_export_vector(
  plot = patchwork,
  filepath = here("Output", "charts", "1_F_couple_moving.svg"),
  bg_col = pw_bg_color
  )


```