---
title: "Migration qualification"
author: "Duc-Quang Nguyen"
date: "2025-05-10"
output: html_document
---

### Load & wranglge

```{r setup & load data, include=FALSE}
source("_helpers.R")
run_n_check <- T
```


```{r wrangle}
c2t_A1 <- read_csv(here("Data", "code2txt", "NCCR MMS Codes A1.csv"))
c2t_B1 <- read_csv(here("Data", "code2txt", "NCCR_MMS_codes - B1.csv"))
c2t_D1 <- read_csv(here("Data", "code2txt", "NCCR_MMS_codes - D1.csv"))
c2t_E38 <- read_csv(here("Data", "code2txt", "NCCR_MMS_codes - E38.csv"))


data_all <- mms_df  %>% 
  ### subset !!!
  select(
    A1, A6, B1, B9, D1, E38, year, weight, everything()
  ) %>% 
  left_join(c2t_A1) %>% 
  left_join(c2t_B1 %>% select(B1, country)) %>% 
  left_join(c2t_D1) %>% 
  left_join(c2t_E38)


data_all %>% filter(is.na(country)) %>% .$B1 %>% unique() %>% sort()

# data_all %>% 
#   group_by(year, groupe_edu) %>% 
#   summarise(
#     tot = sum(weight, na.rm = T)
#   ) %>% 
#   ungroup() %>% 
#   group_by(year) %>% 
#   mutate(
#     toty = sum(tot)
#   ) %>% 
#   ungroup %>% 
#   mutate(
#     share = tot/toty
#   )

```


### La migration est de plus en plus hautement qualifiée

```{r wrangle more & check}
edu_main <- data_all %>% 
  group_by(year, groupe_edu) %>% 
  summarise(
    n = n(),
    weight_sum = sum(weight)
  ) %>% 
  ungroup() %>% 
  group_by(year) %>% 
  mutate(
    toty = sum(n),
    tot_weight = sum(weight_sum)
  ) %>% 
  ungroup %>% 
  mutate(
    share_w = (weight_sum /tot_weight) * 100
  ) 

# check
if(run_n_check) {
  edu_main %>% 
    group_by(year) %>% 
    reframe(n = sum(n))  
}


edu_genre <- data_all %>% 
  group_by(year, groupe_edu, sexe) %>% 
  summarise(
    n = n(),
    weight_sum = sum(weight)
  ) %>% 
  ungroup() %>% 
  group_by(year, sexe) %>% 
  mutate(
    toty = sum(n),
    tot_weight = sum(weight_sum)
  ) %>% 
  ungroup %>% 
  mutate(
    share_w = (weight_sum /tot_weight) * 100
  ) 

edu3_pays <- data_all %>% 
  group_by(year, groupe_edu, country) %>% 
  summarise(
    n = n(),
    weight_sum = sum(weight)
  ) %>% 
  ungroup() %>% 
  group_by(year, country) %>% 
  mutate(
    toty = sum(n),
    tot_weight = sum(weight_sum)
  ) %>% 
  ungroup %>% 
  mutate(
    share_w = (weight_sum /tot_weight) * 100
  ) %>% 
  filter(groupe_edu == "Tertiary")

# du3_pays %>% filter(year == 2022) %>% arrange(desc(share_w))

# check n
if(run_n_check) {
  data_all %>% 
    filter(year == 2018 | year == 2024) %>% 
    group_by(year, groupe_edu, country) %>% 
    summarise(
      n = n(),
    ) %>% 
    ungroup() %>% 
    group_by(year, country) %>% 
    mutate(
      toty = sum(n)
    ) %>% 
    ungroup  %>% 
    group_by(year, country) %>% 
    reframe(
      n = sum(n)
    ) %>% 
    arrange(country) %>% 
    pivot_wider(names_from = year, values_from = n) 
}          
```

#### Main stacked area


```{r color palettes trials, eval = F}
edu_chart_1 <- edu_main %>% 
  ggplot(aes(x = year, y = share_w, group = groupe_edu)) +
  geom_area(aes(fill = groupe_edu), alpha = 1) + 
  theme_mms(grid="XY", axis="xy", 
                 #grid_col =  scales::alpha("lightgrey", 0.5),
                 base_size = mms_base_size,
                 plot_title_size = mms_plot_title_size,
                 subtitle_size = mms_subtitle_size,
                 plot_margin = mms_plot_margin
  ) + 
  theme(legend.position = "none",
        panel.background = element_rect(fill = NA),  # transparent
        panel.ontop = TRUE
  ) +
  # remove any scale expansion
  scale_x_continuous(expand = c(0,0), name = "", breaks = seq(2016, 2024, 2)) +
  # have y scale not start at 0, add unit % 
  scale_y_continuous(expand = c(0,0), name = "", 
                     labels = function(x) paste0(x, "%")) +
  labs(
    title="Part des trois niveaux de formation",
    subtitle="Niveau de formation atteint le plus élevé")


annot_df <- tibble(
  year = rep(2020, 3),
  share_w = c(27, 72, 93),
  txt = c("Tertiaire", "Secondaire II", "Secondaire I")
)

edu_chart_1a <- flush_ticks(edu_chart_1)  +
  geom_richtext(data = annot_df, aes(
    x = year, y = share_w, label = txt, group = 1),
    fill = NA, label.color = NA,# remove background and outline,
    color = "white", size = 5,
    fontface = "bold",
    hjust = 0.5, family = mms_base_family
  )

edu_chart_t1 <- edu_chart_1a +
  scale_fill_manual(values = mms_colors_education()[2:4]) 

edu_chart_t2 <- edu_chart_1a + 
  scale_fill_nccr_categorical()


# patchwork
# (edu_chart1_a + edu_chart2_a) / edu_chart3

svglite::svglite(
  filename = here("Output", "charts", "trials", "edu_colors.svg"),
  height = 11.7,
  width = 8.3,
  fix_text_size = T
  )

edu_chart_t1 / edu_chart_t2

dev.off()


```

```{r main}

edu_chart_1 <- edu_main %>% 
  ggplot(aes(x = year, y = share_w, group = groupe_edu)) +
  geom_area(aes(fill = groupe_edu), alpha = 1) + 
  theme_mms(grid="XY", axis="xy", 
                # grid_col =  scales::alpha("lightgrey", 0.6),
                 base_size = mms_base_size,
                 mms_plot_title = mms_txtbox_plot.title(nrow_txt = 2),
                 plot_title_size = mms_plot_title_size,
                 subtitle_size = mms_subtitle_size,
                 plot_margin = mms_plot_margin_l
  ) + 
  theme(legend.position = "none",
        panel.background = element_rect(fill = NA),  # transparent
        panel.ontop = TRUE
  ) +
  # remove any scale expansion
  scale_x_continuous(expand = c(0,0), name = "", breaks = seq(2016, 2024, 2)) +
  # have y scale not start at 0, add unit % 
  scale_y_continuous(expand = c(0,0), name = "", 
                     breaks = seq(25, 100, 25),
                     labels = function(x) paste0(x, "%")) +
  labs(
    title = str_c("Strong increase in ", 
                  "<span style='color:#6E6C88'>highly skilled</span> migration"),
    subtitle="Highest level of education attained, by survey year") +
  scale_fill_nccr_categorical(order = c(5,6,10))


annot_df <- tibble(
  year = rep(2020, 3),
  share_w = c(27, 72, 93),
  txt = c("Tertiaire", "Secondaire II", "Secondaire I")
)

edu_chart_1a <- edu_chart_1 +
  geom_richtext(data = annot_df, aes(
    x = year, y = share_w, label = txt, group = 1),
    fill = NA, label.color = NA,# remove background and outline,
    color = "white", size = 6, alpha = 0.95,
    #fontface = "bold",
    hjust = 0.5, family = mms_base_family
  )


edu_chart_1a

```


### Line chart by gender

```{r edu 2}
edu_all_genre <- bind_rows(
  edu_main %>% 
    select(year, groupe_edu, share_w, n) %>% 
    mutate(type = "all"),
  edu_genre %>% 
    select(year, sexe, groupe_edu, share_w, n) %>% 
    rename(type = sexe)
) %>%  
  filter(groupe_edu == "Tertiary") %>% 
  mutate(
    al = ifelse(type == "all", 0.7, 1)
  )

edu_genre_rib_df <- edu_all_genre %>% 
  filter(type %in% c("male", "female") & 
           groupe_edu == "Tertiary") %>% 
  select(year, share_w, type) %>% 
  pivot_wider(names_from = type, values_from = share_w)


edu_chart2 <- edu_all_genre %>% 
  mutate(
    type = case_when(
      type == "all" ~ "TOTAL",
      type == "male" ~ "Men",
      type == "female" ~ "Women",
      T ~ type
    )
  ) %>% 
  ggplot(aes(x= year)) +
  geom_ribbon(
    data = edu_genre_rib_df,
    aes(ymin = male, ymax = female, group = 1),
    fill = nccr_bi_colors[13], alpha = 0.15) +
  geom_point(aes(x = year, y = share_w, 
                 group = type,
                 color = type), 
             alpha = 1, size = 3) +
  geom_line(aes(x = year, y = share_w, group = type,
                color = type), alpha = 0.3, 
            linewidth = 1.5,
            lineend="round", show.legend = F) +
  theme_mms(axis="xy", grid = "Y",
                 base_size = mms_base_size,
                 mms_plot_title = mms_txtbox_plot.title(nrow_txt = 2),
                 plot_title_size = mms_plot_title_size,
                 subtitle_size = mms_subtitle_size,
                 plot_margin = mms_plot_margin_r
  ) + 
  scale_size(range = c(0.1, 3)) +
  scale_alpha(range = c(0.5, 1), ) +
  scale_x_continuous(
    breaks =seq(2016, 2024, 2),
    # limits = c(2016,2024),
    expand = c(0.02,0), name = "") +
  # have y scale not start at 0, add unit % 
  scale_y_continuous(expand = c(0.015,0.015), name = "", 
                     labels = function(x) paste0(x, "%"),
                     position = "right") +
  scale_colour_manual(
    values=c(nccr_bi_colors[c(2,13,12)])) +
  # To hide the alpha legend as well:
  guides(color = "none", alpha = "none",
         size = guide_legend(override.aes = list(color = mms_legend_base_col))) +
  geom_text(data=. %>% 
              arrange(desc(year)) %>% 
              group_by(type) %>% 
              slice(1), 
            aes(label=type, y = share_w,
                colour = type), 
            family = mms_base_family,
            #fontface = "bold",
            position=position_nudge(0.3), hjust=0, 
            show.legend=FALSE, size = 3) +
  coord_cartesian(xlim = c(2016, 2026)) 


edu_chart2_a <- edu_chart2 +
  labs(
    title = str_c("<span style='color:",
                  nccr_bi_colors[12], 
                  ";'>Women</span> ",
    "migrants more qualified than <span style='color:", 
    nccr_bi_colors[2], ";'>men"),
    subtitle = "Share with tertiary education, by gender")

edu_chart2_a

```

#### Lollipop by nationality

```{r edu 3}
share_tot_3 <- edu_all_genre %>% 
  filter(year %in% c(2018, 2024) & type == "all") %>% 
  select(year, share_w) %>% 
  mutate(type = "Moyenne")


edu3_pays_df <- edu3_pays %>%
  select(year, country, groupe_edu, share_w, n) %>%
  rename(type = country) %>% 
  filter(year %in% c(2018, 2024)) %>% 
  select(type, year, share_w, n) %>% 
  arrange(year, desc(share_w)) %>% 
   left_join(
    pays2col,
    by = c("type" = "country")
  ) %>% mutate(
    type = fct_reorder(type, share_w, .fun = max, .desc = T)
  ) 

edu3_pays_w <- edu3_pays_df %>% 
  select(-n) %>% 
  pivot_wider(
    names_from = year, values_from = share_w
)  

pc_shift_txt <- 0
edu3_pays_df_sub <- edu3_pays_df %>% 
  group_by(type) %>% 
  reframe(
    share_w = max(share_w)
  ) %>% 
  left_join(
    pays2col,
    by = c("type" = "country")
  ) %>%
  mutate(
    type = fct_reorder(type, share_w, .desc = T)
  ) %>% 
  arrange(desc(share_w)) %>% 
  mutate(
    y = share_w,
    angle = 0#ifelse(share_w > share_tot_3,
            #       90, -90)
  ) %>% 
  mutate(
    # Insert line breaks between words
    labels = gsub(" ", "<br>", type)
  )

nudge_y_txt <- ifelse(
 edu3_pays_df_sub$share_w > share_tot_3, 1, -1
)
nudge_x_txt <- ifelse(
  edu3_pays_df_sub$share_w > share_tot_3, -0.2, +0.2
)

annot_sub <- edu3_pays_df %>% 
  filter(type == "Other Europe") %>% 
  select(type, share_w) %>% 
  mutate(type = as.numeric(type))

# A tibble: 2 × 5
arrow_txt <-
  tibble(
    x1 = annot_sub$type-c(1,1),
    x2 = annot_sub$type,
    y1 = annot_sub$share_w-c(2,2),
    y2 = annot_sub$share_w,
    label = c("2018", "2024")
  )

pt_size <- 3

edu_chart3 <- edu3_pays_df %>% 
  ggplot(aes(x=type, y=share_w)) +
    geom_curve(
    data = arrow_txt,
    aes(x = x1, y = y1, xend = x2, yend = y2),
    color = nccr_bi_colors[13], 
    alpha = 0.5,
    curvature = 0.2, size = .3) +
  geom_richtext(
    data = arrow_txt, 
    aes(x = x1, y = y1, label = label),
    family = mms_base_family,
    #fontface ="bold",
    fill = NA, label.color = NA,# remove background and outline,
    color = nccr_bi_colors[13], size = 4,
    hjust = 1, vjust = 0.5
  ) +
  geom_point(
    data = edu3_pays_df %>% 
      filter(year == 2024), 
    aes(color = color, group = year),
    alpha = 1, shape = 17, size = pt_size) + 
  geom_point(
    data = edu3_pays_df %>% filter(year == 2018),
    aes(color = color, group = year),
    size = pt_size,
    alpha = 1, shape = 15, show.legend = F) + 
  geom_segment(
    data = edu3_pays_w,
    aes(x=type, xend=type, y=`2018`, yend=`2024`,
        color = color, alpha = 0.4), linewidth = 1, show.legend = F) +
  theme_mms(grid="Y", axis="y") + 
  theme(
    legend.position = c(0.05, 0.13),
    legend.text = element_text(size = 8, 
                               color = mms_legend_base_col), # Reduce legend text size
    legend.title = element_text(
      size = 8, color = mms_legend_base_col, 
      face = "bold", hjust =0.5), # Reduce legend title size
      legend.key.size = unit(0.8, "lines"), # Reduce legend key size
  ) +
  scale_x_discrete(name = "", labels = NULL) +
  scale_y_continuous(name = "", 
                     limits = c(
                       min(edu3_pays_df$share_w), 
                       max(edu3_pays_df$share_w) + 3.5),
                     labels = function(x) paste0(x, "%")) +
  scale_size_continuous(range = c(1, 4)) +
  geom_richtext(
    data = edu3_pays_df_sub,
    aes(label = labels, x = type, y = share_w,
        angle = angle,
        color = color),
    fill = NA, label.color = NA,# remove background and outline,
    size = 3.3,
    hjust = 0.5, 
    vjust = 0,
    family = mms_base_family,
    nudge_y = 1
  ) +
  scale_color_identity() +
  labs(
    title = "Migrants from Asia and Eastern Europe most likely to hold tertiary degrees",
    subtitle = "Change in tertiary education rate between 2018 and 2024, by country of origin"
  ) + 
  guides(size = guide_legend(override.aes = list(color = mms_legend_base_col))) 

edu_chart3

```

### patchwork


```{r patch}

patchwork <- (edu_chart_1a + edu_chart2_a) / edu_chart3

mms_export_vector(
  plot = patchwork,
  filepath = here("Output", "charts", "A_education.svg"),
  bg_col = pw_bg_color
  )


```
