---
title: "MMS_NCCR_template"
author: "Duc-Quang Nguyen"
date: "2025-05-10"
output: html_document
---

```{r setup & load data, include=FALSE}
source("Scripts/_helpers.R")
run_n_check <- T
```


```{r wrangle}
c2t_A1 <- read_csv(here("Data", "code2txt", "NCCR MMS Codes A1.csv"))
c2t_B1 <- read_csv(here("Data", "code2txt", "NCCR_MMS_codes - B1.csv"))
c2t_E38 <- read_csv(here("Data", "code2txt", "NCCR_MMS_codes - E38.csv"))



data_all <- mms_df  %>% 
  ### subset !!!
  left_join(c2t_A1) %>% 
  left_join(c2t_B1) %>% 
  left_join(c2t_E38 %>% select(-edu_details)) %>% 
  mutate(
    migy = mms_encode_migration_year(A6,year)
  ) %>% 
  left_join(
    migy2yearIntervals) 
  # select(
  #   A1, A6, B1, B9, E38, year, weight, everything()
  # )  
    
d_df <- data_all %>% 
  select(year:mig_4y)

```


```{r wrangle & check}
# 1 by years since 2018
ints_df <- d_df %>% 
  filter(year >= 2018) %>% 
  filter(!is.na(groupe_job_edu)) %>% 
  group_by(year, groupe_job_edu) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
    #share = round(weight/sum(weight, na.rm = TRUE)*100, 1)
  ) %>% 
  group_by(year) %>% 
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = round(weight/sum(weight, na.rm = TRUE)*100, 1)
  ) %>% 
  ungroup() %>% 
  select(year, groupe_job_edu, share, n_y,n, weight) %>% 
  # create coords for donut chart https://r-graph-gallery.com/128-ring-or-donut-plot.html
  group_by(year) %>% 
  mutate(
    ymax = cumsum(share),
    ymin = c(0, head(ymax, n=-1)),
    # Compute label position
    label_pos = (ymax + ymin) / 2,
    # Compute a good label
    label = paste0(share, "%")
  ) %>% 
  ungroup()


if(run_n_check) {
  ints_df %>% 
    select(year, n_y, groupe_job_edu, share) %>%
    pivot_wider(
      names_from = groupe_job_edu,
      values_from = share
    ) 
}

# 2 by 4 years migration intervals 
ints_migy_df <- d_df %>%
  filter(!is.na(mig_4y)) %>%
  filter(!is.na(groupe_job_edu)) %>%
  group_by(mig_4y, groupe_job_edu) %>%
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
    #share = round(weight/sum(weight, na.rm = TRUE)*100, 1)
  ) %>% 
  group_by(mig_4y) %>% 
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = round(weight/sum(weight, na.rm = TRUE)*100, 1)
  ) %>% 
  ungroup() %>% 
  select(mig_4y, groupe_job_edu, share, n_y,n, weight) 

if(run_n_check) {
  ints_migy_df %>% 
    select(mig_4y, n_y, groupe_job_edu, share) %>%
    pivot_wider(
      names_from = groupe_job_edu,
      values_from = share
    )
}

# 3. By country
ints_pays_df <- d_df %>% 
  filter(year == 2024) %>% 
  filter(!is.na(country)) %>% 
  filter(!is.na(groupe_job_edu)) %>% 
  group_by(country, groupe_job_edu) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
    #share = round(weight/sum(weight, na.rm = TRUE)*100, 1)
  ) %>% 
  group_by(country) %>% 
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = round(weight/sum(weight, na.rm = TRUE)*100, 1)
  ) %>% 
  ungroup() %>% 
  select(country, groupe_job_edu, share, n_y,n, weight) %>% 
  mutate(
    country = fct_reorder(country, share, .fun = max, .desc = T)
  ) %>% 
  arrange(country, desc(share))

if(run_n_check) {
  ints_pays_df %>% 
    select(country, n_y, groupe_job_edu, share) %>%
    pivot_wider(
      names_from = groupe_job_edu,
      values_from = share
    )
}
```

### Viz 

#### 1. 
```{r main chart}
# Create a data frame for the year labels to avoid overplotting
year_labels <- distinct(ints_df, year)

# faceted pie donut chart by year
p_ints_1 <- ints_df %>% 
 ggplot(
   aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=groupe_job_edu)) +
  geom_rect(color = "white") +
  geom_label(
    x=3.5, aes(y=label_pos, label=label), size=2.5,
    fill = NA, label.size = 0, 
    color = "white", 
    family = mms_base_family) +
  facet_wrap(~year) +
  coord_polar(theta="y") + # Try to remove that to understand how the chart is built initially
 # 
  #theme_void() +
  theme_mms(
    grid=F, 
    axis=F,
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 3),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 2)
  ) +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    legend.position = "none",
       #panel.spacing = unit(-50, "cm"),
    panel.spacing.y = unit(-10, "pt"),  # reduce space between facets
    # strip.text = element_text(angle = 0, hjust = 0.5,
    #                           # remove margin
    #                           margin = margin(b = 0, t = 10))# 0 = left,
    # This removes the default facet titles (the grey strips)
    strip.text = element_blank(),
    strip.background = element_blank()
  ) +
  scale_fill_manual(values = nccr_categorical()[c(7,11)]) +
  scale_y_continuous(name = "", expand = c(0, 0)) +
  scale_x_continuous(name = "", expand = c(0, 0), limits = c(2, 4)) +
  labs(
    title = "Most people consider their education suited to their job, with little change over time",
    subtitle = str_c("Share of people who consider their education",
                     "<span style='color:", nccr_categorical()[11], "'> 'is suited' </span> vs. ", 
                     "<span style='color:", nccr_categorical()[7], "'> 'not suited' </span>",
    " to their job, by year since 2018")
  ) +
  # place the year inside the donut in the middle and remove facet text title
  geom_text(
    data = year_labels, # Use a dedicated data frame with one row per year
    aes(x = 2, y = 0, label = year), # Position text at the center
    inherit.aes = FALSE, # IMPORTANT: Prevents inheriting aesthetics from ggplot()
    size = 4,
    family = mms_base_family
  )

p_ints_1
```


#### 2.
```{r 2}

p_ints_2 <- ints_migy_df %>% 
  filter(groupe_job_edu == "Yes") %>% 
  ggplot(aes(x = mig_4y, y = share, group = 1)) +
  geom_line(aes(linewidth  = n_y), 
            color =nccr_categorical()[11],
            alpha = 0.2, lineend = "round")  +
  geom_point(
    aes(size = n_y), alpha = 1,
    color = nccr_categorical()[11]
  ) +
  theme_mms(grid="Y",
            axis = T,
            mms_txtbox_plot.title(nrow_txt = 2),
            mms_txtbox_plot.subtitle(nrow_txt = 3)#,
            #plot_margin = margin(15, 20, 50, 10)
            
  ) + 
  theme(
    legend.position = c(0.85, 0.9),
    legend.key.height = unit(0.7, "lines"),
    #legend.spacing.y = unit(0.01, "lines"),
    legend.text = element_text(size = 8, 
                               color = mms_legend_base_col), # Reduce legend text size
    legend.title = element_text(size = 10, 
                                color = mms_legend_base_col, 
                                face = "bold", 
                                hjust =0.5) # Reduce legend title size
  ) +
  guides(
    size = guide_legend(
      override.aes = list(
        color = mms_legend_base_col,  # This makes the legend points grey
        fill = mms_legend_base_col    # Just in case the theme uses fill
      )
    )
  )+
  scale_y_continuous(expand = c(0.047,0.012), 
                     name = "", 
                     labels = function(x) paste0(x, "%")) +
  labs(
    x = "", y = "",
    subtitle = "Share of people who consider their education is suited to their job, by migration year intervals",
    title = "Early migrants report a better skill match for their jobs",
    size = "n",
    linewidth = "n"
  )

p_ints_2
```


#### 3. 
```{r 3}

ints_pays_ordered <- ints_pays_df %>% 
  filter(groupe_job_edu == "Yes") %>% 
  mutate(
    country = factor(country) %>% fct_reorder(share, .desc = T)
  ) %>% 
  arrange(country) %>% 
  .$country %>% as.character()

ints2mekko_df <- mms_mekko_wrangler(
  ints_pays_df %>% 
    mutate(
      country = factor(country, levels = ints_pays_ordered),
      groupe_job_edu = factor(groupe_job_edu),
    ) %>% 
    mutate(groupe_job_edu = fct_rev(groupe_job_edu)) %>% 
    arrange(country, groupe_job_edu),
  var1 = "groupe_job_edu", 
  var2 = "country", 
  varv = "share", 
  tot_n = "n_y"
) %>% 
  left_join(pays2col) %>% 
  mutate(
    color = ifelse(groupe_job_edu == "No", "white", color)
  ) 

p_ints_3 <- ints2mekko_df %>%   
  ggplot() +
  geom_rect(
    aes(xmin = xmin, xmax = xmax, 
        ymin = ymin, ymax = ymax,
        fill = color),
    colour = "white", 
    size = 1, alpha = 1) +
  scale_fill_identity() +
  theme_mms(
    grid="X", axis=F,
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 3),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 4)
  ) + 
  theme(
    legend.position = "none",
    plot.margin = mms_plot_margin
  ) + 
  scale_x_continuous(name = "", expand = c(0,0), position = "top",
                     labels = function(x) paste0(x, "%"),
                     breaks = NULL) +
  scale_y_continuous(name = "",  labels = NULL, expand = c(0,0))

#p_ints_3


ints_pays_labels <- ints2mekko_df %>%
  filter(groupe_job_edu == "Yes") %>%
  mutate(y = ymax - 0.01, yRange = (ymax - ymin)* 100) %>%
  select(country, xmin, y, yRange) %>%
  ungroup() %>% 
  mutate(
    # Insert line breaks between words
    labels = country#gsub(" ", "<br>", country)
  ) %>% 
  # weird fix
  mutate(
    labels = ifelse(labels == "Other countries",
                    "", labels)
  )

ints_value_labels <- ints2mekko_df %>% 
  filter(groupe_job_edu == "Yes") %>% 
  select(country, groupe_job_edu, xmin, xmax, ymin, ymax, share) %>%
  mutate(
    x = xmax,
    y = ymax - 0.01,
    label = paste0(round(share, 1), "%"),
    hjust = ifelse(groupe_job_edu == "Yes", 1.05, -0.05)
  ) 

p_ints_3a <- p_ints_3 +
   geom_richtext(
    data = ints_pays_labels,
    aes(x = xmin + 0.01, y = y, 
        label = labels),
    fill = NA, label.color = NA,# remove background and outline,
    size = 4,
    hjust = 0, nudge_x = .5, vjust = 1, colour = "white",
    family = mms_base_family
  ) +
  geom_richtext(
    data = ints_value_labels,
    aes(x = x + 0.01, y = ymin, label = label, hjust = hjust),
    fill = NA, label.color = NA,# remove background and outline,
    vjust = 0, nudge_y = 0.005, size = 3, alpha = 0.95, colour = "white",
    family = mms_base_family
   ) 
  #+ labs(
  #   title = str_c("Citizens from <span style='color:", col_voisin, ";'>neighboring countries</span> are more likely to arrive in Switzerland with a job"),
  #   subtitle = str_c("Job secured before moving to Switzerland, by country of origin in 2024"),
  #   caption = str_c("Bar height is proportional to sample size (n), total respondents: ",#,
  #                   fpp2mekko_df$n %>% sum()%>% prettyNum(big.mark = " ")
  #   )
  # )

  p_ints_3a

```