---
title: "Increasing share of people reporting family-related migration"
author: "Duc-Quang Nguyen"
date: "2025-05-10"
output: html_document
---

```{r setup & load data, include=FALSE}
source("_helpers.R")
run_n_check <- T
```


```{r wrangle}
c2t_A1 <- read_csv(here("Data", "code2txt", "NCCR MMS Codes A1.csv"))
c2t_B1 <- read_csv(here("Data", "code2txt", "NCCR_MMS_codes - B1.csv"))
#mms_encode_yes_no_code

b8 <- mms_load_data(F) %>% 
  select(B8_3, B8_4, B8_11)


data_all <- bind_cols(mms_df, b8)  %>% 
  left_join(c2t_A1) %>% 
  ### subset !!!
  left_join(c2t_B1) 

e_df <- data_all %>% 
  select(year:country, B9) %>% 
  mutate(
    famr = ifelse(B8_3 == 1 | B8_4 == 1 | B8_11 == 1, "yes", "no")
  ) %>% 
  mutate(
    famr = ifelse(is.na(famr), "no", famr)
  )
```

```{r wrangle & check}
fam_sexe_df <- e_df %>% 
  filter(year > 2016) %>% 
  filter(!is.na(famr)) %>% 
  filter(!is.na(sexe)) %>% 
  group_by(year, sexe, famr) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>% 
  group_by(year,sexe) %>% 
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100
  ) %>% 
  ungroup() %>% 
  select(year, famr, sexe, share, n_y,n, weight) %>% 
  filter(famr == "yes") %>% 
  select(-famr, -n, -weight)
  
  
# fam_tog_df <- fam_sexe_df %>% 
#   group_by(year) %>% 
#   reframe(
#     sexe = 'ensemble',
#     share = sum(share) / n(),
#     n_y = sum(n_y)
#   )
#   
  
fam_tog_df <- tibble(
  year = c(2024, 2022, 2020, 2018),
  sexe = "together",
  share = c(44.6, 44.3, 41.2, 38.9),
  n_y = c(6969, 7205, 7390, 7736)
)  %>%
  arrange(desc(year))

fam_sexe_df <- bind_rows(fam_sexe_df, fam_tog_df) 


if(run_n_check) {
  fam_sexe_df %>%
    select(year, n_y, sexe, share) %>%
    pivot_wider(
      names_from = sexe,
      values_from = c(share, n_y)
    )
}

fam_pays_df <- e_df %>% 
  filter(year == 2024) %>% 
  filter(!is.na(famr)) %>% 
  filter(!is.na(pays)) %>% 
  group_by(country, famr) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>% 
  group_by(country) %>% 
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = round(weight/sum(weight, na.rm = TRUE)*100, 1)
  ) %>% 
  ungroup() %>% 
  select(country, famr, share, n_y,n, weight) %>% 
  #filter(famr == "yes") %>% 
  #select(-famr, -n, -weight) %>% 
  filter(country != "Other countries")


if(run_n_check) fam_pays_df

```

### VIZ

# 1. main line chart

```{r 1}

famr_1 <- fam_sexe_df %>% 
  ggplot(aes(x = year, y = share, group = sexe)) +
  geom_line(aes(color=sexe),
             linewidth = 2,
            alpha = 0.3) +
  geom_textline(
    aes(label = sexe, color = sexe), size = 4, 
    vjust = -0.3,
    linewidth = 0, family = mms_base_family) +
  geom_point(aes(
    color = sexe),
    size = 4) +
  theme_mms(
    grid="Y", axis=T,
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 3),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 3)
  ) +
  scale_color_manual(values = nccr_bi_colors[c(12,2,14)]) +
  scale_x_continuous(
    name = "", expand = c(0.05,0.05)
  ) +
  scale_y_continuous(name = "", 
                     n.breaks = 10,
                     labels = function(x) paste0(x, "%"),
                     expand = c(0.05,0.05)
  ) +
  guides(color = "none") +
  labs(
    title = "Increase in the share of people reporting family-related reasons for moving to Switzerland",
    subtitle = "Share of people reporting family-related reasons for moving to Switzerland, by survey year",
    size = "n", linewidth = "n"
  )

famr_1
```


#### 2 country mekko chart
```{r 2}
fam_pays_ordered <- fam_pays_df %>% 
  filter(famr == "yes") %>% 
  mutate(
    country = factor(country) %>% 
      fct_reorder(share, .desc = T)
  ) %>% 
  arrange(country) %>% 
  .$country %>% as.character()

fam2mekko_df <- mms_mekko_wrangler(
  fam_pays_df %>% 
    mutate(
      country = factor(country, levels = fam_pays_ordered),
      pays = factor(country),
      famr = factor(famr, levels = c("yes", "no")),
      n_y = 1,
    ) %>% 
    arrange(country, famr),
  var1 = "famr", 
  var2 = "country", 
  varv = "share", 
  tot_n = "n_y"
) %>% 
  left_join(pays2col) %>% 
  filter(famr != "no")


famr_2 <- fam2mekko_df %>%   
  ggplot() +
  geom_rect(
    aes(xmin = xmin, xmax = xmax, 
        ymin = ymin, ymax = ymax,
        fill = color),
    colour = "white", 
    size = 2, alpha = 1) +
  scale_fill_identity() +
  theme_mms(
    grid=F, axis=F,
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 3),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 3)
  ) + 
  theme(
    legend.position = "none"
  ) + 
  scale_x_continuous(name = "", expand = c(0,0), position = "top",
                     labels = function(x) paste0(x, "%"),
                     breaks = NULL) +
  scale_y_continuous(name = "",  labels = NULL, expand = c(0,0))

famr_pays_labels <- fam2mekko_df %>%
  filter(famr == "yes") %>%
  mutate(y = ymax - 0.007, yRange = (ymax - ymin)* 100) %>%
  select(country, xmin, y, yRange) %>%
  ungroup() %>% 
  mutate(
    # Insert line breaks between words
    labels = country#gsub(" ", "<br>", country)
  ) 

famr_value_labels <- fam2mekko_df %>% 
  filter(famr == "yes") %>% 
  select(country, famr, xmin, xmax, ymin, ymax, share) %>%
  mutate(
    x = xmax,
    y = ymax - 0.01,
    label = paste0(round(share, 1), "%"),
    hjust = ifelse(famr == "yes", 1.05, -0.05)
  ) 

famr_2a <- famr_2 +
   geom_richtext(
    data = famr_pays_labels,
    aes(x = xmin + 0.01, y = y, 
        label = labels),
    fill = NA, label.color = NA,# remove background and outline,
    size = 4,
    hjust = 0, nudge_x = 0.5, vjust = 1, colour = "white",
    family = mms_base_family
  ) +
  geom_richtext(
    data = famr_value_labels,
    aes(x = x + 0.01, y = ymin, label = label, hjust = hjust),
    fill = NA, label.color = NA,# remove background and outline,
    vjust = 0, nudge_y = 0.005, size = 3, alpha = 0.95, colour = "white",
    family = mms_base_family
   ) + 
  labs(
    title = str_c("Family-related migration more common among non-EU Europeans, Africans, and Latin Americans"),
    subtitle = str_c("Share of people reporting they came to Switzerland for family reunification, by country of origin in 2024")
  )

famr_2a
```


```{r patch}
patchwork <- famr_1 + famr_2a 
patchwork

mms_export_vector(
  plot = patchwork,
  filepath = here("Output", "charts", "E_family_reunification.svg"),
  bg_col = pw_bg_color
  )


```