---
title: "MMS_NCCR_template"
author: "Duc-Quang Nguyen"
date: "2025-05-10"
output: html_document
---

```{r setup & load data, include=FALSE}
source("_helpers.R")
run_n_check <- T
```


```{r load}
# gender
c2t_A1 <- read_csv(here("Data", "code2txt", "NCCR MMS Codes A1.csv"))
# pays 
c2t_B1 <- read_csv(here("Data", "code2txt", "NCCR_MMS_codes - B1.csv"))

data_all <- mms_df  %>% 
  left_join(c2t_A1) %>% 
  left_join(c2t_B1) %>% 
  mutate(
    hh3 = case_when(
      F1 == 1 ~ "1 person",
      F1 == 2 ~ "2 people",
      F1 >= 3 ~ "3+ people",
      TRUE ~ NA
    )
  )

g_df <- data_all %>% 
  select(year:hh3)
```


```{r wrangle & check}
hh_y_df <- g_df %>% 
  filter(!is.na(hh3)) %>% 
  filter(!is.na(year)) %>% 
  group_by(year, hh3) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>%
  group_by(year) %>%
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100
  ) %>% 
  ungroup()

if(run_n_check) {
  hh_y_df %>% 
    select(year, hh3, share, n_y) %>%
    pivot_wider(
      names_from = hh3,
      values_from = share
    ) 
}


hh_g_df <- g_df %>% 
  filter(year == 2024) %>%
  filter(!is.na(hh3)) %>% 
  filter(!is.na(sexe)) %>% 
  group_by(sexe, hh3) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>%
  group_by(sexe) %>%
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100
  ) %>% 
  ungroup()

if(run_n_check) {
  hh_g_df %>% 
    select(sexe, hh3, share, n_y) %>%
    pivot_wider(
      names_from = hh3,
      values_from = share
    )
}

hh_c_df <- g_df %>% 
  filter(year == 2024) %>%
  filter(!is.na(hh3)) %>% 
  filter(!is.na(country)) %>% 
  group_by(country, hh3) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>%
  group_by(country) %>%
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100
  ) %>% 
  ungroup()

if(run_n_check) {
  hh_c_df %>% 
    select(country, hh3, share, n_y) %>%
    pivot_wider(
      names_from = hh3,
      values_from = share
    ) 
}
```



### VIZ

#### 1. main  chart

```{r 1 }

hh_y_labels <- tibble(
  year = c(2022, 2022, 2022),
  share = c(13,68, 95),
  label = rev(c("1 person", "2 people", "3+ people"))
)

p_hh_1 <- hh_y_df %>% 
  ggplot(aes(x = factor(year), y = share, fill = hh3)) +
  geom_area(aes(group = hh3), alpha = 1) +
  # geom_text(
  #   aes(label = paste0(round(share, 1), "%")),
  #   alpha = 0.8,
  #   size = 3, position = position_stack(vjust = 0.9),
  #   family = mms_base_family, color = "white") +
  geom_richtext(
    data = hh_y_labels,
    aes(x = factor(year), y = share, label = label),
    size = 7, 
    color = "white",
    #angle = 90,
    fill = NA, label.color = NA, family = mms_base_family,
    vjust = 1, hjust = 1, nudge_x = 0.5
  ) +
  theme_mms(
    grid="Y", axis="XY",
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 1),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 1)
  ) + 
  theme(
    legend.position = "none",
    panel.ontop = TRUE,
    panel.background = element_rect(fill = NA),
    panel.grid.major.y = element_line(color = "white",
                                      linetype = "dashed", linewidth = 0.2) # Make grid lines more visible
   # axis.text.y = element_blank()
  ) +
  # remove any scale expansion
  scale_x_discrete(expand = c(0,0), name = "") +
  # have y scale not start at 0, add unit % 
  scale_y_continuous(expand = c(0,0), name = "", 
                     breaks = seq(25, 100, 25),
                     labels = function(x) paste0(x, "%")) +
  scale_fill_manual(values = nccr_categorical()[c(13, 3, 4)]) +
  labs(
    title = str_c("Over half of households have ", 
                    '<span style="color:', nccr_categorical()[4], ';">three or more members'),
    subtitle = "Number of household members"
  )



p_hh_1
```

#### 2. by gender   

```{r 2}

hh_g_labels <- tibble(
  sexe = 1:2,
  label = rev(c("men", "women")),
  share = rep(4,2)
)

p_hh_2 <- hh_g_df %>% 
 ggplot(aes(x = sexe, y = share, fill = hh3)) +
  geom_bar(stat = "identity", position = "fill") +
  geom_text(aes(y = share / 100, label = paste0(round(share), "%")), size = 3,
            position = position_stack(vjust = 0.8), family =mms_base_family,
            color = "white") +
   geom_richtext(data = hh_g_labels, 
                 aes(x = as.numeric(sexe), y = share / 100, 
                     label = label),
                 color = "white",
                 fill = NA, family = mms_base_family,
                hjust = 0.5,  label.color = NA, size = 6
    #  fontface = "bold"
  ) +
  #coord_flip(clip = "on") +
  scale_fill_manual(values = nccr_categorical()[c(13, 3, 4)]) +
  theme_mms(
    grid="", axis="",
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 3),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 2)
  ) + 
  theme(
    legend.position = "none",
    axis.text.y = element_blank(),
    axis.text.x = element_blank()
  ) +
    # remove any scale expansion
  scale_x_discrete(expand = c(0,0), name = "") +
  # have y scale not start at 0, add unit % 
  scale_y_continuous(expand = c(0,0), name = "") +
   labs(
    title = str_c("Men are more likely to live ", 
                    '<span style="color:', nccr_categorical()[14], ';">alone', "</span> than women"),
    subtitle = "Number of household members, by gender in 2024"
  )

p_hh_2

```

#### 3. by country

```{r 3 mekko}
hh_pays_ordered <- hh_c_df %>% 
  filter(hh3 == "1 person") %>% 
  mutate(
    country = factor(country) %>% fct_reorder(share, .desc = T)
  ) %>% 
  arrange(country) %>% 
  .$country %>% as.character()


hh2mekko_df <- mms_mekko_wrangler(
  hh_c_df %>% 
    filter(country != "Other countries") %>%
    mutate(
      country = factor(country, levels = hh_pays_ordered),
      hh3 = factor(hh3), 
      n_y = 1,
    ) %>% arrange(country, hh3),
  var1 = "hh3", 
  var2 = "country", 
  varv = "share", 
  tot_n = "n_y"
) 

# job labels tibble
hh_pays_labels <- hh2mekko_df %>%
  filter(hh3 == "3+ people") %>%
  mutate(y = ymax - 0.01, yRange = (ymax - ymin)* 100) %>%
  select(country, xmax, y, yRange) %>%
  ungroup() %>% 
  mutate(
    # Insert line breaks between words
    labels = gsub(" ", "<br>", country)
  )


hh_value_labels <- hh2mekko_df %>% 
  select(country, hh3, xmin, xmax, ymin, ymax, share) %>%
  mutate(
    x = xmin,
    y = ymax - 0.01,
    label = paste0(round(share, 1), ifelse(hh3 == "3+ people", "%", "")),
    hjust = -0.05,
    color = ifelse(hh3 == "1 person", "black", "white")
  ) 

hh_ph_labels <- tibble(
  y = rep(0.52, 3),
  share = c(7,34, 68),
  label = c("1 person", "2 people", "3+ people")
)


p_hh_3 <- hh2mekko_df %>%   
  ggplot() +
  geom_rect(
    aes(xmin = xmin, xmax = xmax, 
        ymin = ymin, ymax = ymax,
        fill = hh3),
    colour = "white", #nccr_bi_colors[13]
    size = 1, alpha = 1) +
  theme_mms(
    grid="X", axis=F,
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 3),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 2)
  ) + 
  theme(
    legend.position = "none"
  ) + 
  scale_fill_manual(values = nccr_categorical()[c(13, 3, 4)]) +
  scale_x_continuous(name = "", expand = c(0,0), 
                     # position = "top",
                     # labels = function(x) paste0(x, "%"),
                     breaks = NULL
                     ) +
  scale_y_continuous(name = "",  labels = NULL, expand = c(0,0))


p_hh_3a <- p_hh_3 +
  geom_richtext(
    data = hh_pays_labels,
    aes(x = xmax - 1, y = y, 
        label = labels),
    fill = NA, label.color = NA,# remove background and outline,
    size = 4,
    hjust = 1, nudge_x = .5, vjust = 1, colour = "white",
    family = mms_base_family
  ) +
  geom_richtext(
    data = hh_value_labels,
    aes(x = x - 0.005, y = ymin, label = label, hjust = hjust, color = color),
    fill = NA, label.color = NA,# remove background and outline,
    vjust = 0, nudge_y = 0.002, size = 3, alpha = 0.95,
    family = mms_base_family
  ) +
  geom_richtext(
    data = hh_ph_labels,
    aes(x = share, y = y, label = label),
    fill = NA, label.color = NA,# remove background and outline,
    size = 6,
    alpha = 0.4,
    hjust = 0.5, nudge_x = 0.5, vjust = 1, colour = "white",
    family = mms_base_family,
    angle = 90
  ) +
  scale_color_identity() +
   labs(
     title = str_c("Higher proportion of people <span style='color:", nccr_categorical()[14], ";'>living alone</span> among citizens of the European Union"),
     subtitle = str_c("Number of household members, by country of origin in 2024")
   )


p_hh_3a
```

#### patch


```{r patchwork}
patchwork <- (p_hh_1 /p_hh_2) +
   plot_layout(heights = c(1, 1)) | p_hh_3a 
patchwork

patchwork



mms_export_vector(
  plot = patchwork,
  filepath = here("Output", "charts", "G_household_size.svg"),
  bg_col = pw_bg_color
  )


```