---
title: "More than half of migrants are interested in naturalization"
author: "Duc-Quang Nguyen"
date: "2025-05-10"
output: html_document
---

```{r setup & load data, include=FALSE}
source("_helpers.R")
run_n_check <- T
```

```{r load}
# gender
c2t_A1 <- read_csv(here("Data", "code2txt", "NCCR MMS Codes A1.csv"))
# pays 
c2t_B1 <- read_csv(here("Data", "code2txt", "NCCR_MMS_codes - B1.csv"))

c3 <- mms_load_data(F) %>% 
  select(C3_1:C3_9)

c1_codes <- tibble(
 C1 = c(1, 2, 3, 4, 5, 6, 7),
 nat = c("yes", "yes", "no", "no", "don't know", "yes", "yes")
)

data_all <- bind_cols(mms_df, c3)  %>%  
  # hack in 2024 C1 column is named c1
  mutate(
    C1 = ifelse(year == 2024, c1, C1)
  ) %>% 
  left_join(
    c1_codes, by = "C1"
  ) %>% 
  left_join(c2t_A1) %>% 
  left_join(c2t_B1) %>% 
  mutate_at(vars(C3_1:C3_9), ~ case_when(
    . == 1 ~ "yes",
    . == 2 ~ "no",
    TRUE ~ NA_character_
  )) %>% 
  mutate(  
    migy = mms_encode_migration_year(A6,year)
  ) %>% 
  left_join(
    migy2yearIntervals
  )

h_df <- data_all %>% 
  select(year:mig_4y)
```


```{r wrangle & check}
nati_y_df <- h_df %>% 
  filter(year > 2016) %>% 
  filter(!is.na(nat)) %>%
  filter(!is.na(year)) %>%
  group_by(year, nat) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>%
  group_by(year) %>%
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100
  ) %>% 
  ungroup() 

  
  
if(run_n_check) {
  nati_y_df %>% 
    select(year, nat, share, n_y) %>%
    pivot_wider(
      names_from = nat,
      values_from = share
    )
}


### manual data 
# nati_migy_df  <- tibble(
#   yeari = rep(c("2010—2014", "2006—2009"), 5),
#   year = as.integer(rep(c(2024, 2022, 2020, 2018, 2016), each = 2)),
#   share = c(70.9, 78.2, 67.1, 74.3, 61.7, 68.7, 53.2, 62.1, 38.9, 45.3)
# )

nati_migy_df <- h_df %>% 
  filter(!is.na(nat)) %>%
  filter(!is.na(year)) %>%
  filter( 
    (migy >= 2010 & migy <= 2014) |
      (migy >= 2006 & migy <= 2009)  
  ) %>% 
  mutate(
    yeari = case_when(
      migy >= 2010 & migy <= 2014 ~ "2010—2014",
      migy >= 2006 & migy <= 2009 ~ "2006—2009",
      TRUE ~ NA_character_
    )
  ) %>% 
  group_by(year, yeari, nat) %>%
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>%
  group_by(year, yeari) %>%
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100
  ) %>% 
  ungroup() %>% 
  filter(nat == "yes") %>% 
  select(-nat)

if(run_n_check) {
  nati_migy_df %>% 
    select(year, yeari, share) %>% 
    pivot_wider(
      names_from = yeari,
      values_from = share
    )
}


nati_c_df <- h_df %>% 
  filter(!is.na(nat)) %>% 
  filter(!is.na(country)) %>% 
  group_by(country, year, nat) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>%
  group_by(country, year) %>%
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100
  ) %>% 
  ungroup() %>% 
  filter(nat == "yes") %>% 
  left_join(pays2col) %>% 
  filter(country != "Other countries") 

if(run_n_check) {
  nati_c_df %>% 
    select(country, year, share) %>%
    pivot_wider(
      names_from = year,
      values_from = share
    )
}

nati_cr_df1 <- h_df %>% 
  filter(year == 2024) %>% 
  filter(!is.na(country)) %>% 
  filter(!is.na(C3_4) | !is.na(C3_5)) %>% 
  group_by(C3_4, country) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>% 
  group_by(country) %>%
  reframe(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100,
    val = C3_4
  ) %>% 
  filter(val == "yes") %>% 
  mutate(C3 = "C3_4") %>% 
  select(-val)
  
nati_cr_df2 <- h_df %>% 
  filter(year == 2024) %>% 
  filter(!is.na(country)) %>% 
  filter(!is.na(C3_4) | !is.na(C3_5)) %>% 
  group_by(C3_5, country) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>% 
  group_by(country) %>%
  reframe(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100,
    val = C3_5
  ) %>% 
  filter(val == "yes") %>% 
  mutate(C3 = "C3_5") %>% 
  select(-val)

nati_cr_df <- bind_rows(nati_cr_df1, nati_cr_df2) %>% 
  filter(country != "Other countries") 


if(run_n_check) {
  nati_cr_df %>% 
    select(country, C3, share, n_y) %>%
    pivot_wider(
      names_from = C3,
      values_from = c(share, n_y)
    ) %>%
    arrange(desc(share_C3_4))
}
```



### VIZ

#### 1. main  chart

```{r 1}
p_nati_1 <- nati_y_df %>% 
  ggplot(aes(x = year, y = share, group = nat)) +
  geom_area(aes(fill = nat), alpha = 1) + 
  theme_mms(grid="XY", axis="xy", 
            #grid_col =  scales::alpha("lightgrey", 0.6),
            base_size = mms_base_size,
            mms_plot_title = mms_txtbox_plot.title(nrow_txt = 3),
            mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 3)
  )  + 
  theme(legend.position = "none",
        panel.background = element_rect(fill = NA),  # transparent
        panel.ontop = TRUE
  ) +
  # remove any scale expansion
  scale_x_continuous(expand = c(0,0), name = "", breaks = seq(2016, 2024, 2)) +
  # have y scale not start at 0, add unit % 
  scale_y_continuous(expand = c(0,0), name = "", 
                     labels = function(x) paste0(x, "%")) +
  labs(
    title = str_c("The share of people ", 
                  "<span style='color:#678E6F'>interested in naturalization</span> is gradually increasing"),
    subtitle="Do you plan to apply for Swiss naturalization in the future?") +
  scale_fill_nccr_categorical(order = c(7,13,12))


annot_df <- tibble(
  year = rep(2021, 3),
  share_w = c(36, 69, 88),
  txt = c("Yes", "Don't know", "No")
)


p_nati_1a  <-p_nati_1  +
  geom_richtext(data = annot_df, aes(
    x = year, y = share_w, label = txt, group = 1),
    fill = NA, label.color = NA,# remove background and outline,
    color = "white", size = 5, alpha = 1,
    #fontface = "bold",
    hjust = 0.5, family = mms_base_family
  )
p_nati_1a

```

#### 2. Line charts

```{r 2}

nati_migyw_df <- nati_migy_df %>% 
  select(yeari, year, share) %>%
  pivot_wider(
    names_from = yeari,
    values_from = share
  ) %>% 
  mutate(group = 1)

p_nati_2 <- nati_migy_df %>% 
  ggplot(aes(x = year)) +
  geom_ribbon(
    data = nati_migyw_df,
    aes(ymin = `2010—2014`, ymax = `2006—2009`, x = year),
    alpha = 0.2, fill = nccr_bi_colors[12]
  ) +
  geom_line(aes(y = share, color=yeari),
            linewidth = 1,
            alpha = 0.5) +
  geom_textline(
    aes(y = share, label = yeari, color = yeari), size = 4, 
    vjust = -0.2,
    linewidth = 0, family = mms_base_family) +
  geom_point(aes(
    y = share,
    color = yeari),
    size = 3) +
  theme_mms(
    grid="Y", axis=T,
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 3),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 3)
  ) +
  scale_color_manual(values = nccr_bi_colors[c(12,2)]) +
  scale_x_continuous(
    name = "", expand = c(0.05,0.05)
  ) +
  scale_y_continuous(name = "", 
                     n.breaks = 10,
                     labels = function(x) paste0(x, "%"),
                     expand = c(0.05,0.05)
  ) +
  guides(color = "none") +
  labs(
    title = "A steady increase over time spent in Switzerland",
    subtitle = "Share of people intending to naturalize, by arrival cohort"
  )

p_nati_2
```

#### 3. small multiples country chart

```{r 3}
nati_c_df %<>% 
  mutate(
    country_styled = str_c(
      "<span style='color:", color, "'>", country, "</span>"
    ) %>% factor %>% fct_reorder(share, .fun = max, .desc = TRUE)
  )

fl_points <- nati_c_df %>%
  group_by(country_styled) %>%
  slice(c(1,5)) %>% 
  ungroup()

l_points <- nati_c_df %>%
  group_by(country_styled) %>%
  slice(c(5)) %>% 
  ungroup()

# Create the data frame for the labels
year_label_df <- tibble(
  x = c(2016, 2024),
  label = c(2016, 2024),
  hjust = c(0, 1) # 0 for left-align, 1 for right-align
)


p_nati_3 <- nati_c_df %>% 
  ggplot(aes(x = year, y = share, colour = color)) +
  geom_line(alpha = 0.9, show.legend = FALSE, linewidth = 1) +
  geom_point(
    data  = fl_points, size = 2
  ) +
  gghighlight(
    use_direct_label = F,
     unhighlighted_params = list(linewidth = .4, alpha = 0.4, size = 0)
  ) +
  ggrepel::geom_text_repel(
    data = fl_points,
    aes(label = paste0(round(share, 0), "%")),
    size = 3,
    nudge_y = -10,
    direction = "y",
    hjust = 0,
    segment.color = NA,
    family = mms_base_family
  ) +
  #  # Add the custom labels using the new data frame
  # geom_text(
  #   data = year_label_df,
  #   aes(x = x, y = -Inf, label = label, hjust = hjust),
  #   vjust = 1, # Nudge text down, below the plot panel
  #   inherit.aes = FALSE
  # ) +
  facet_wrap(~country_styled, ncol = 4) +
  theme_mms(grid=F, axis=F, 
            grid_col =  scales::alpha("lightgrey", 0.6),
            mms_plot_title = mms_txtbox_plot.title(nrow_txt = 2),
            mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 3)
  )  + 
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    panel.spacing.x = unit(0, "lines"),
    panel.spacing.y = unit(1, "lines"),
    strip.text = element_markdown(size = 9,
                                  hjust = 0.5,
                                  margin = margin(b = 0, t = 1))
  ) +
  # remove any scale expansion
  scale_x_continuous(expand = c(0.05,0.05), name = "") +
  # have y scale not start at 0, add unit % 
  scale_y_continuous(expand = c(0.02,0.02), name = "", 
                     labels = function(x) paste0(x, "%")) +
  labs(
    title = "Interest in naturalization varies by country of origin",
    subtitle = "Share of people intending to naturalize, by country of origin from 2016 until 2024"
  ) +
  scale_color_identity()

p_nati_3

```

#### 4. Reasons for naturalization

```{r 4}

o_countries <- nati_cr_df %>% 
  filter(C3 == "C3_4") %>%
  mutate(
    country =  factor(country) %>% fct_reorder(share, .fun = mean, .desc = TRUE)
  ) %>% .$country %>% levels()

nati_cr_labels <- nati_cr_df %>%
  group_by(country) %>% 
  reframe(
    y = 0,
    c3_4 = -share[which(C3 == "C3_4")],
    c3_5 = share[which(C3 == "C3_5")],
    # Insert line breaks between words
    labels =  as.character(country) #gsub(" ", "<br>", as.character(country))
  )

# mirror column plot
nati_cr_df %<>% 
 mutate(
   sshare = ifelse(C3 == "C3_4", -share, share),
   country = factor(country, levels = rev(o_countries))
 ) 

p_nati_4 <- nati_cr_df %>% 
 ggplot() +
  geom_col(aes(x=country, y=sshare, fill=C3)) +
  coord_flip(clip = "off") +
  theme_mms(
    grid="X", axis="X",
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 3),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 6)
  ) +
  scale_fill_manual(values = nccr_bi_colors[c(2,9)]) +
  scale_y_continuous(expand = c(0,0), name = "", 
                     # limits = c(-85, 50),
                     breaks = NULL
                     #labels = function(x) paste0(abs(x), "%")
                     ) +
  scale_x_discrete(expand = c(0,0), name = "",
                   labels = NULL) +
  theme(
    legend.position = "none"
  ) +
  geom_richtext(
    data = nati_cr_labels,
    aes(x = country, y = y-0.1, 
        label = labels),
    fill = NA, label.color = NA,# remove background and outline,
    size = 3.5,
    hjust = 1, nudge_x = 0, vjust = 0.5, colour = "white",
    family = mms_base_family
   ) +
  geom_richtext(
    data = nati_cr_labels,
    aes(x = country, y = c3_4, label = paste0(abs(round(c3_4)), "%"),
        hjust = 0),
    fill = NA, label.color = NA,# remove background and outline,
    vjust = 0.5, nudge_x = 0, size = 2.5, alpha = 0.95, colour = "white",
    family = mms_base_family
  ) +
  geom_richtext(
    data = nati_cr_labels,
    aes(x = country, y = c3_5, label = paste0(abs(round(c3_5)), "%"),
        hjust = 1),
    fill = NA, label.color = NA,# remove background and outline,
    vjust = 0.5, nudge_x = 0, size = 2.5, alpha = 0.95, colour = "white",
    family = mms_base_family
  ) +
  annotate("text", x = nlevels(nati_cr_df$country), y = 0,
           label = "Improved professional\nopportunities", vjust = -1, hjust = 0, 
           size = 3,
           family = mms_base_family, fontface = "bold",
           color = nccr_bi_colors[10]) +
  annotate("text", x = nlevels(nati_cr_df$country), y = -27,
           label = "\nSense of belonging", vjust = -1, hjust = 1, 
           size = 3,
           family = mms_base_family, fontface = "bold",
           color = nccr_bi_colors[2]) +
  
  labs(
    title = str_c("Sense of belonging and career advancement as main drivers for naturalization"),
    subtitle = str_c("Proportion of people citing 'a sense of belonging' versus 'improved professional opportunities' as reasons for seeking naturalization, 2024 (multiple responses allowed)<br><br>")
  )

p_nati_4
```

#### patch

```{r patch}

# patchwork <- p_nati_1a / (p_nati_2 | p_nati_3) / p_nati_4 +
#   plot_layout(heights = c(1, 1, 1))
# 
# patchwork <- ((p_nati_1a /p_nati_3) +
#   plot_layout(heights = c(1,2), widths = 1, ncol = 1) | (p_nati_2/p_nati_4) +
#     plot_layout(heights = c(1,2),  widths = 1, ncol = 1)) +
#   plot_layout(widths = c(1,1))
# patchwork

patchwork <- ((p_nati_1a /p_nati_2) +
  plot_layout(heights = c(1,1), widths = 1, ncol = 1) | (p_nati_3/p_nati_4) +
    plot_layout(heights = c(1.5,1),  widths = 1, ncol = 1)) +
  plot_layout(widths = c(1,1.7))
patchwork




mms_export_vector(
  plot = patchwork,
  filepath = here("Output", "charts", "H_naturalization.svg"),
  bg_col = pw_bg_color
  )


```