---
title: "K Friendship"
author: "Duc-Quang Nguyen"
date: "2025-05-10"
output: html_document
---

```{r setup & load data, include=FALSE}
source("_helpers.R")
run_n_check <- T
```


```{r load}
# pays 
c2t_B1 <- read_csv(here("Data", "code2txt", "NCCR_MMS_codes - B1.csv"))

g62f <- tibble(
  G6 = 1:5,
  g6 = c(rep("(Mostly) in Switzerland", 2), "Mixed", rep("(Mostly) abroad", 2))
)
g202f <-  tibble(
  G20 = 1:2,
  g20 = c("Yes", "No")
)

data_all <- mms_df %>% 
  mutate(migy = mms_encode_migration_year(A6,year)) %>% 
  left_join(g62f, by = c("G6")) %>%
  left_join(g202f, by = c("G20")) %>%
  left_join(migy2yearIntervals) %>%
  left_join(c2t_B1) 


k_df <- data_all %>% 
  select(year:country) 

```

### Wrangle & check

```{r wrangle & check}
fri_df <- k_df %>% 
  filter(year > 2016) %>%
  filter(!is.na(g6)) %>% 
  group_by(year, g6) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>%
  group_by(year) %>%
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100
  ) %>%
  ungroup() %>% 
  mutate(
    g6 = factor(g6, levels = g62f$g6[c(1,3,5)])
  )

if(run_n_check) {
  fri_df %>% 
    select(year, g6, share, n_y) %>%
    pivot_wider(
      names_from = g6,
      values_from = share
    )
}

frim_df <- k_df %>% 
  filter(year == 2024) %>% 
  filter(!is.na(g6)) %>% 
  filter(!is.na(mig_4y)) %>% 
  group_by(mig_4y, g6) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>%
  group_by(mig_4y) %>%
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100
  ) %>%
  ungroup() %>% 
  mutate(
    g6 = factor(g6, levels = g62f$g6[c(1,3,5)])
  )


if(run_n_check) {
  frim_df %>% 
    select(mig_4y, g6, share, n_y) %>%
    pivot_wider(
      names_from = g6,
      values_from = share
    )
}

# by country
fric_df <- k_df %>% 
  filter(year == 2024) %>% 
  filter(!is.na(g6)) %>% 
  filter(!is.na(country)) %>% 
  group_by(country, g6) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>%
  group_by(country) %>%
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100
  ) %>%
  ungroup() %>% 
  filter(country != "Other countries") 

# Create a helper data frame with just the sorting values
country_order_df <- fric_df %>%
  filter(g6 == g62f$g6[1]) %>%
  select(country, sorting_value = share)

# Join the sorting values back and then reorder the factor
fric_df %<>%
  mutate(
    country = factor(
      country, levels = country_order_df$country)
  )

if(run_n_check) {
  fric_df %>% 
    select(country, g6, share, n_y) %>%
    pivot_wider(
      names_from = g6,
      values_from = share
    )
}

# by g20 and mig_4y
frimg_df <- k_df %>% 
  filter(year == 2024) %>% 
  filter(!is.na(g20)) %>% 
  filter(!is.na(mig_4y)) %>% 
  group_by(mig_4y, g20) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>%
  group_by(mig_4y) %>%
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100
  ) %>%
  ungroup()

if(run_n_check) {
  frimg_df %>% 
    select(mig_4y, g20, share, n_y) %>%
    pivot_wider(
      names_from = g20,
      values_from = share
    )
}
```



### VIZ

#### 1. main  chart

```{r 1}
annot_df <- tibble(
  year = rep(2021, 3),
  share_w = c(22, 55, 87),
  txt = g62f$g6[rev(c(1,3,5))]
)

p_fri_1 <- fri_df %>% 
  ggplot(aes(x = year, y = share, group = g6)) +
  geom_area(
    aes(fill = g6), 
    alpha = 1) +
  theme_mms(
    grid="XY", axis="XY", 
   # grid_col =  scales::alpha("lightgrey", 0.6),
     plot_margin = mms_plot_margin_l,
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 5),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 5)
  )  +
  theme(legend.position = "none",
        panel.background = element_rect(fill = NA),  # transparent
        panel.ontop = TRUE
  ) +
  # remove any scale expansion  
  scale_x_continuous(expand = c(0,0), name = "", 
                     breaks = seq(2018, 2024, 2)) +
  # have y scale not start at 0, add unit %
  scale_y_continuous(expand = c(0,0), name = "", 
                     breaks = seq(25, 100, 25),
                     labels = function(x) paste0(x, "%")) +
  labs(
    title = str_c("The location of friends' residence shows little change between 2018 and 2024"),
    subtitle = str_c(
      "Friends' place of residence: ",
      "<span style='color:", nccr_bi_colors[7], ";'>mostly in Switzerland</span>, ", 
       "<span style='color:", nccr_bi_colors[13], ";'>mixed</span> or ",      
      "<span style='color:", nccr_bi_colors[3], ";'>mostly abroad</span>, ",
      " by survey year"
    )) +
  scale_fill_manual(values =nccr_bi_colors[c(7,13,3)]) +
  geom_richtext(data = annot_df, aes(
    x = year, y = share_w, label = txt, group = 1),
    fill = NA, label.color = NA,# remove background and outline,
    color = "white", size = 5, alpha = 1,
    #fontface = "bold",
    hjust = 0.5, family = mms_base_family
  )

p_fri_1
```

#### 2.   

```{r 2}
p_fri_2 <- frim_df %>% 
  ggplot(aes(x = mig_4y, y = share, fill = g6)) +
  geom_bar(stat = "identity", position = "stack", alpha = 1) +
  theme_mms(
    grid=F, axis=F, 
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 5),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 5)
  ) +
  theme(
    legend.position = "none",
    panel.background = element_rect(fill = NA),  # transparent
    panel.ontop = TRUE
  ) +
  scale_x_discrete(expand = c(0.05,0.05), name = "") +
  scale_y_continuous(name = "", 
                     breaks = NULL,
                    # n.breaks = 10,
                    # labels = function(x) paste0(x, "%"),
                     expand = c(0,0)
  ) +
  scale_fill_manual(values = nccr_bi_colors[c(7,13,3)]) +
  labs(
    title = str_c("Friends' place of residence differs by respondents' migration history"),
    subtitle = str_c(
      "Friends' place of residence in 2024, by respondents' migration year: ",
      "<span style='color:", nccr_bi_colors[7], ";'>mostly in Switzerland</span>, ", 
       "<span style='color:", nccr_bi_colors[13], ";'>mixed</span> or ",      
      "<span style='color:", nccr_bi_colors[3], ";'>mostly abroad</span>"
    )
  ) +
  geom_text(data = frim_df %>% filter(g6 == g62f$g6[1]), 
            aes(y = 100 - share, label = paste0(round(share, 1), "%")), 
            vjust = 0, nudge_y = 2,
            size = 3, color = "white", family = mms_base_family) +
  geom_text(data = frim_df %>% filter(g6 == g62f$g6[5]),
            aes(y = share, label = paste0(round(share, 1), "%")), 
            vjust = 1, nudge_y = -2,
            size = 3, color = "white", family = mms_base_family)

p_fri_2
```

#### 3.

```{r 3}
ordered_c <- fric_df %>% 
  filter(g6 == g62f$g6[1]) %>% 
  mutate(
    country = fct_reorder(country, share, .desc = TRUE)
  ) %>% 
  .$country %>% levels()

fric_df %<>%
  mutate(
    country = factor(country, levels = rev(ordered_c))
  )

fric_1_df <- fric_df %>% 
  filter(g6 == g62f$g6[1])

fric_2_df <- fric_df %>% 
  filter(g6 == g62f$g6[5]) %>% 
  mutate(
    label_share = share,
    share = 100-share
  )

fric_3_df <- left_join(
  fric_1_df %>% 
    rename(xstart = share),
  fric_2_df %>%
    rename(xend = share) %>% 
  select(country, xend)
)
  
segm_lw <- 2
point_size <- 4
nudge_y_txt <- 0.3

# lollipop chart by country
p_fri_3 <- fric_df %>% 
  ggplot() +
  geom_segment(data = fric_3_df,
               aes(x = xstart, xend = xend, y = country, yend = country), 
               color = nccr_bi_colors[13], size = segm_lw) +
  geom_segment(data = fric_1_df, 
               aes(x = 0, xend = share, y = country, yend = country), 
               color = nccr_bi_colors[7], size = segm_lw, alpha = 0.8) +
  geom_point(data = fric_1_df, 
             aes(x = share, y = country, color = g6), size = point_size,
             color = nccr_bi_colors[7]) +
  geom_segment(data = fric_2_df, 
               aes(x = 100, xend = share, y = country, yend = country), 
               color = nccr_bi_colors[3], size = segm_lw, alpha = 0.8) +
  geom_point(data = fric_2_df, aes(x = share, y = country,
                                   color = g6), size = point_size,
             color = nccr_bi_colors[3]) +
  theme_mms(
    grid=F, axis=F, 
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 5),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 5)
  ) +
  theme(
    # legend.position = "none",
    # panel.background = element_rect(fill = NA),  # transparent
    # panel.ontop = TRUE
    axis.text.y = element_text(hjust = 1)
  ) +
  scale_x_continuous(name = "", 
                     breaks = NULL,# seq(0, 100, 20),
                    # labels = function(x) paste0(x, "%"),
                     expand = c(0.01,0.01)
                    ) +
  scale_y_discrete(name = "") +
  scale_color_manual(values = nccr_bi_colors[c(7,13,3)]) +
  labs(
    title = str_c("Italians have friends in many locations, while the Spanish and Portuguese tend to have friends in their country of origin"),
    subtitle = str_c(
      "Friends' place of residence in 2024, by country: ",
      "<span style='color:", nccr_bi_colors[7], ";'>mostly in Switzerland</span>, ", 
       "<span style='color:", nccr_bi_colors[13], ";'>mixed</span> or ",      
      "<span style='color:", nccr_bi_colors[3], ";'>mostly abroad</span>"
    )
  ) +
  geom_text(data = fric_1_df, 
            aes(x = share, y = country, 
                label = paste0(round(share, 0), "%")), 
            vjust = 0, hjust = 0.5, nudge_y = nudge_y_txt,
            size = 2.5, color = nccr_bi_colors[8], family = mms_base_family) +
  geom_text(data = fric_2_df,
            aes(x = share, y = country, 
                label = paste0(round(label_share, 0), "%")), 
            vjust = 0, hjust = 0.5, nudge_y = nudge_y_txt,
            size = 2.5, color = nccr_bi_colors[3], family = mms_base_family)


p_fri_3
```

#### 4.

```{r 4}
frimg_y_labels <- frimg_df %>% 
  filter(g20 == "Yes")

frimg_n_labels <- frimg_df %>% 
  filter(g20 == "No")

p_fri_4 <- frimg_df %>% 
  ggplot(aes(x = mig_4y, y = share)) +
  geom_bar(aes(fill = g20), stat = "identity", position = "stack", alpha = 1) +
  theme_mms(
    grid=F, axis=F, 
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 5),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 5)
  ) +
  theme(
    legend.position = "none"
  ) +
  scale_x_discrete(expand = c(0.,0), name = "") +
  scale_y_continuous(name = "", 
                     breaks = NULL,
                     expand = c(0,0)
  ) +
  scale_fill_manual(values = nccr_bi_colors[c(7,3)]) +
  labs(
    title = str_c("Most respondents have someone in Switzerland they can count on. Especially those who arrived long time ago compared to recent arrivals"),
    subtitle = str_c(
      "Presence, ",
      "<span style='color:", nccr_bi_colors[4], ";'>yes</span> or ",
      "<span style='color:", nccr_bi_colors[8], ";'>no</span>, ",
      "of a person to count on in Switzerland in 2024, by year of migration"
    )
  ) +
  geom_text(data = frimg_y_labels, 
            aes(y = share, label = paste0(round(share), "%")), 
            vjust = 1, nudge_y = -3,
            size = 3, color = "white", family = mms_base_family) +
  geom_text(data = frimg_n_labels,
            aes(y = 100 - share, label = paste0(round(share), "%")), 
            vjust = 0, nudge_y = 3,
            size = 3, color = "white", family = mms_base_family)

p_fri_4

```

#### patch

```{r patch}
# On crée une ligne du haut, puis une ligne du bas
top_row <- (p_fri_1 | p_fri_3)
bottom_row <- (p_fri_2 | p_fri_4)

# On les place l'une sur l'autre
patchwork <- (top_row / bottom_row) + 
  plot_layout(heights = c(1.5, 1)) # On garde le contrôle des largeurs

patchwork


mms_export_vector(
  plot = patchwork,
  filepath = here("Output", "charts", "K_friendship.svg"),
  bg_col = pw_bg_color
  )


```