---
title: "L homesickness"
author: "Duc-Quang Nguyen"
date: "2025-05-10"
output: html_document
---

```{r setup & load data, include=FALSE}
source("_helpers.R")
run_n_check <- T
```


```{r load}
# gender
c2t_A1 <- read_csv(here("Data", "code2txt", "NCCR MMS Codes A1.csv"))
# pays 
c2t_B1 <- read_csv(here("Data", "code2txt", "NCCR_MMS_codes - B1.csv"))

G26 <- mms_load_data(F) %>% 
  select(G26_1)

g262f <-  tibble(
  G26_1 = 0:7,
  g26 = c(
   rep("weak",3),
   rep("moderate",2),
   rep("strong", 3)
  )
)

data_all <- bind_cols(mms_df, G26) %>% 
  mutate(migy = mms_encode_migration_year(A6,year)) %>% 
  left_join(migy2yearIntervals) %>%
  left_join(g262f) %>% 
  left_join(c2t_A1) %>%
  left_join(c2t_B1) 

l_df <- data_all %>% 
  select(year:country) %>% 
  filter(year == 2024) %>% 
  mutate(
    g26 = factor(g26, levels = g262f$g26[c(1,5,8)]),
  )
```

### Wrangle & check

```{r wrangle & check}
l_df %>% 
  filter(!is.na(g26)) %>% 
  filter(!is.na(year)) %>% 
  filter(year == 2024) %>% 
  group_by(sexe, g26) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>%
  group_by(sexe) %>%
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100
  ) %>% 
  ungroup() %>% 
  select(sexe, g26, share, n_y) -> ho_g_df

if(run_n_check) {
  ho_g_df %>% 
    select(sexe, g26, share, n_y) %>%
    pivot_wider(
      names_from = g26,
      values_from = share
    )
}
l_df %>% 
  filter(!is.na(g26)) %>% 
  filter(!is.na(country)) %>% 
  group_by(country, g26) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>%
  group_by(country) %>%
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100
  ) %>% 
  ungroup() %>% 
  select(country, g26, share, n_y) %>% 
  filter(country != "Other countries") -> ho_c_df
  
if(run_n_check) {
  ho_c_df %>% 
    select(country, g26, share, n_y) %>%
    pivot_wider(
      names_from = g26,
      values_from = share
    )
}

# by migration mig_4y
l_df %>% 
  filter(!is.na(g26)) %>% 
  filter(!is.na(mig_4y)) %>% 
  group_by(mig_4y, g26) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>%
  group_by(mig_4y) %>%
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100
  ) %>% 
  ungroup() %>% 
  select(mig_4y, g26, share, n_y) -> ho_m_df

if(run_n_check) {
  ho_m_df %>% 
    select(mig_4y, g26, share, n_y) %>%
    pivot_wider(
      names_from = g26,
      values_from = share
    )
}


## colors
genderg_col <- nccr_categorical()[c(3,3,4)]
genderg_col[1] <- desaturate(genderg_col[1], 0.6) %>% lighten(0.35)
genderg_col[3] <- darken(genderg_col[3], 0.1) 



```



### VIZ

#### 1. main  chart

```{r 1}
ho_g_df %<>% 
  select(sexe, g26, share, n_y) %>% 
  # create coords for donut chart https://r-graph-gallery.com/128-ring-or-donut-plot.html
  group_by(sexe) %>% 
  mutate(
    ymax = cumsum(share),
    ymin = c(0, head(ymax, n=-1)),
    # Compute label position
    label_pos = (ymax + ymin) / 2,
    # Compute a good label
    label = paste0(round(share, num_n_dect), "%")
  ) %>% 
  ungroup()

gender_labels <-tibble(
  sexe = distinct(ho_g_df, sexe) %>% deframe(),
  label = c("women", "men"),
  color = nccr_bi_colors[c(12,2)]
)


p_ho_1 <- ho_g_df %>%
 ggplot(
   aes(ymax=ymax, ymin=ymin, xmax=4.5, xmin=3, fill=g26)) +
  geom_rect(color = "white") +
  geom_label(
    x=3.7,
    aes(y=label_pos, label=label, color = ifelse(g26 == g262f$g26[1], "black",  "white"),
    group = rev(g26)), size=4,
    fill = NA, label.size = 0,
    family = mms_base_family) +
  facet_wrap(~sexe, nrow = 2) +
  coord_polar(theta="y") + # Try to remove that to understand how the chart is built initially
  theme_mms(
    grid=F, 
    axis=F,
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 4),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 4)
  ) +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    legend.position = "none",
    panel.spacing = unit(0, "pt"),  # reduce space between facets
    # strip.text = element_text(angle = 0, hjust = 0.5,
    #                           # remove margin
    #                           margin = margin(b = 0, t = 10))# 0 = left,
    # This removes the default facet titles (the grey strips)
    strip.text = element_blank(),
    strip.background = element_blank()
  ) +
  scale_fill_manual(values = genderg_col) +
  scale_y_continuous(name = "", expand = c(0, 0)) +
  scale_x_continuous(name = "", expand = c(0, 0), limits = c(2, 4.5)) +
  labs(
    title = str_c("Homesickness is more common among ",
                  "<span style='color:", nccr_categorical()[12], ";'>women",
                  "</span> than <span style='color:", nccr_bi_colors[2], ";'>",
                  "men</span>"),
    subtitle = str_c("Reported homesickness in 2024, by gender: ",
                   "<span style='color:", darken(genderg_col[1], 0.2), ";'><b>weak</span></b>, ",
                   "<span style='color:", genderg_col[2], ";'><b>moderate</span></b>",
                   " or <span style='color:", darken(genderg_col[3], 0.2), ";'><b>strong</span></b> "
                     )
  ) +
  scale_color_identity() +
  # place the year inside the donut in the middle and remove facet text title
  geom_text(
    data = gender_labels, # Use a dedicated data frame with one row per year
    aes(x = 2, y = 0, label = label, color = color), # Position text at the center
    inherit.aes = FALSE, # IMPORTANT: Prevents inheriting aesthetics from ggplot()
    size = 4,
    family = mms_base_family#, fontface = "bold"
  )

p_ho_1
```

#### 2.   

```{r 2}
# stacked columns by migration intervals
p_ho_2 <- ho_m_df %>% 
  ggplot(aes(x = mig_4y, y = share, fill = rev(g26)), group = rev(g26)) +
  geom_col(position = "fill", color = "white", size = 0.2) +
  theme_mms(
    grid=F, axis=F,
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 4),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 4)
  ) +
  theme(
    legend.position = "none"
  ) +
  # remove any scale expansion  
  scale_x_discrete(expand = c(0,0), name = "") +
  # have y scale not start at 0, add unit %
  scale_y_continuous(expand = c(0,0), name = "",
                     breaks = NULL,
                     labels = function(x) paste0(x*100, "%")) +
  scale_fill_manual(values = rev(genderg_col)) +
  labs(
    title = str_c("People who migrated more recently tend to feel more homesick"),
    subtitle = str_c("Reported homesickness by migration year intervals: ",
                   "<span style='color:", darken(genderg_col[1], 0.2), ";'><b>weak</span></b>, ",
                   "<span style='color:", genderg_col[2], ";'><b>moderate</span></b>",
                   " or <span style='color:", darken(genderg_col[3], 0.1), ";'><b>strong</span></b> "
                     )
  ) +
   # Ajoute cette couche geom_text
  geom_text(
    # L'étiquette est la valeur 'share', formatée en pourcentage
    aes(y = share / 100, 
        label = paste0(round(share, num_n_dect), ifelse(g26 == g262f$g26[1], "%", "")),
        color = ifelse(g26 == g262f$g26[1], "black",  "white"),
        group = rev(g26)), 
    # La magie est ici : on empile les étiquettes comme les barres
    # et on les centre verticalement (vjust = 0.5)
    position = position_stack(vjust = 0.5),
    # Choisis une couleur qui ressort bien, et ajuste la taille
   # color = "white", 
    size = 3.5,
    family = mms_base_family
  ) +
  scale_color_manual(values = c("black" = darken(genderg_col[3], 0.3), 
                                "white" = "white"))


p_ho_2
  

```

#### 3.

```{r 3}
ordered_c <- ho_c_df %>%
  filter(g26 == g262f$g26[1]) %>%
  mutate(
    country = fct_reorder(country, share, .desc = F)
  ) %>%
  .$country %>% levels()

ho_c_df %<>%
  mutate(
    country = factor(country, levels = rev(ordered_c))
  ) %>% 
  arrange(country)


ho_c_labels <- ho_c_df %>%
  group_by(country) %>%
  summarise(
    weak = sum(share[g26 == g262f$g26[1]]),
    mid = sum(share[g26 ==g262f$g26[4]]),
    mid_pos = (weak + (mid/2)) / 100,
    strong = sum(share[g26 == g262f$g26[7]])
  ) %>%
  mutate(
    weak_lbl = paste0("<span style='color:", darken(genderg_col[3], 0.3), ";'>", round(weak, num_n_dect), "%</span>"),
    mid_lbl = paste0("<span style='color:", "white", ";'>", round(mid, num_n_dect), "</span>"),
    strong_lbl = paste0("<span style='color:", "white", ";'>", round(strong, num_n_dect), "</span>")
  ) %>%
  mutate(
    y = 0.005,
    # Insert line breaks between words
    labels = gsub(" ", "<br>", as.character(country))
  )


p_ho_3 <- ho_c_df %>% 
  ggplot(aes(x = country, y = share)) +
  geom_col(aes( fill = rev(g26), group = rev(g26)), position = "fill", color = "white", linewidth = 0.2) +
  coord_flip(clip = "off") +
  theme_mms(
    grid="X", axis=F,
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 4),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 4)
  ) + 
  theme(
    legend.position = "none",
    axis.text.y = element_blank(),
    panel.grid.major = element_blank(),
    axis.text.x = element_text(size = 13, hjust = 0.35)
  ) +
 scale_y_continuous(
    name = "", expand = c(0, 0),
    breaks = NULL,
    position = "right"
  ) +
  scale_x_discrete(expand = c(0, 0), name = "") +
  scale_fill_manual(values = rev(genderg_col)) +
  labs(
  title = str_c("People from Portugal and from far away countries tend to feel more homesick"),
    subtitle = str_c("Reported homesickness in 2024 by country: ",
                   "<span style='color:", darken(genderg_col[1], 0.2), ";'><b>weak</span></b>, ",
                   "<span style='color:", genderg_col[2], ";'><b>moderate</span></b>",
                   " or <span style='color:", darken(genderg_col[3], 0.1), ";'><b>strong</span></b> "
                     )
  ) +
  geom_richtext(
    data = ho_c_labels,
    aes(x = country, y = weak/100,
        label = weak_lbl),
    fill = NA,
    family = mms_base_family,
    hjust = 1, label.color = NA, size = 3.5
  ) +
  geom_richtext(
    data = ho_c_labels,
    aes(x = country, y = 1, label = strong_lbl),
    family = mms_base_family,
    hjust = 1, fill = NA, label.color = NA, size = 3.5
  ) +
  geom_richtext(
    data = ho_c_labels,
    aes(x = country, y = mid_pos, label = mid_lbl),
    family = mms_base_family,
    hjust = 1, fill = NA, label.color = NA, size = 3.5
  ) +
  geom_richtext(
    data = ho_c_labels,
    aes(x = country, y = y,
        label = labels),
    fill = NA, label.color = NA,# remove background and outline,
    size = 4,
    color = "black",#darken(genderg_col[3], 0.3),
    hjust = 0, nudge_x = 0, vjust = 0.5,
    family = mms_base_family#, fontface = "bold"
  ) 


p_ho_3

```

#### patch

```{r patch}
left_col <- (p_ho_1 + p_ho_2) + plot_layout(ncol = 1, heights = c(1.4, 1))

patchwork <- (left_col | p_ho_3) + plot_layout(widths = c(1, 1.35))
patchwork

mms_export_vector(
  plot = patchwork,
  filepath = here("Output", "charts", "L_homesickness.svg"),
  bg_col = pw_bg_color
  )


```