---
title: "N News & politics interest"
author: "Duc-Quang Nguyen"
date: "2025-05-10"
output: html_document
---

```{r setup & load data, include=FALSE}
source("_helpers.R")
run_n_check <- T
```


```{r load}

G26 <- mms_load_data(F) %>% 
  select(G13_1:G13_2, G16_1:G16_2) 

g132f <- tibble(
  G13 = 0:7,
  g13 = c(
   rep("low",3),
   rep("moderate",2),
   rep("high", 3)
  )
)

g162f <- tibble(
  G16 = 1:4,
  g16 = c("low", "low", "moderate", "high")
)


data_all <- bind_cols(mms_df, G26) %>% 
  mutate(migy = mms_encode_migration_year(A6,year)) %>% 
  left_join(g132f, by = c("G13_1" = "G13")) %>%
  left_join(g132f, by = c("G13_2" = "G13"), suffix = c("_ch", "_home")) %>%
  left_join(g162f, by = c("G16_1" = "G16")) %>%
  left_join(g162f, by = c("G16_2" = "G16"), suffix = c("_ch", "_home")) %>% 
  left_join(migy2yearIntervals) 

n_df <- data_all %>% 
  select(year:mig_4y) 

```

### Wrangle & check

```{r wrangle & check}
nic_df <- n_df %>% 
  filter(year >= 2024) %>% 
  filter(!is.na(g13_ch)) %>%
  filter(!is.na(mig_4y)) %>%
  group_by(mig_4y, g13_ch) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>%
  group_by(mig_4y) %>%
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100
  ) %>%
  ungroup() %>% 
  mutate(
    g13_ch = factor(g13_ch, levels = g132f$g13[c(1,5,8)])
  ) %>% 
  arrange(mig_4y, g13_ch)

if(run_n_check) {
  nic_df %>% 
    select(mig_4y, g13_ch, share, n_y) %>%
    pivot_wider(
      names_from = g13_ch,
      values_from = share
    )
}

nih_df <- n_df %>% 
  filter(year >= 2024) %>% 
  filter(!is.na(g13_home)) %>%
  filter(!is.na(mig_4y)) %>%
  group_by(mig_4y, g13_home) %>%
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>%
  group_by(mig_4y) %>%
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100
  ) %>%
  ungroup() %>% 
  mutate(
    g13_home = factor(g13_home, levels = g132f$g13[c(1,5,8)])
  ) %>% 
  arrange(mig_4y, g13_home)

if(run_n_check) {
  nih_df %>% 
    select(mig_4y, g13_home, share, n_y) %>%
    pivot_wider(
      names_from = g13_home,
      values_from = share
    )
}


nipc_df <- n_df %>% 
  filter(year >= 2024) %>% 
  filter(!is.na(g16_ch)) %>%
  filter(!is.na(mig_4y)) %>%
  group_by(mig_4y, g16_ch) %>%
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>%
  group_by(mig_4y) %>%
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100
  ) %>%
  ungroup() %>% 
  mutate(
    g16_ch = factor(g16_ch, levels = g132f$g13[c(1,5,8)])
  ) %>% 
  arrange(mig_4y, g16_ch)

if(run_n_check) {
  nipc_df %>% 
    select(mig_4y, g16_ch, share, n_y) %>% 
    pivot_wider(
      names_from = g16_ch,
      values_from = share
    )
}

niph_df <- n_df %>% 
  filter(year >= 2024) %>% 
  filter(!is.na(g16_home)) %>%
  filter(!is.na(mig_4y)) %>%
  group_by(mig_4y, g16_home) %>%
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>%
  group_by(mig_4y) %>%
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100
  ) %>%
  ungroup() %>% 
  mutate(
    g16_home = factor(g16_home, levels = g132f$g13[c(1,5,8)])
  ) %>% 
  arrange(mig_4y, g16_home)

if(run_n_check) {
  niph_df %>% 
    select(mig_4y, g16_home, share, n_y) %>%
    pivot_wider(
      names_from = g16_home,
      values_from = share
    )
}

```



### VIZ

#### 1. main  chart

```{r 1}

ni_cols <- nccr_bi_colors[c(1,1,2)]
ni_cols[1] <- lighten(ni_cols[1], 0.4) %>% desaturate(0.5)

nih_cols <- nccr_bi_colors[c(11,11,12)]
nih_cols[1] <- lighten(nih_cols[1], 0.4) %>% desaturate(0.5)

box_col <- nccr_bi_colors[13] %>% lighten(0.8)


clabel_size <- 12
vlabel_size <- 3.5

p_ni_1a <- nic_df %>% 
  ggplot(aes(x = mig_4y)) +
  geom_col(aes(y = share, fill = g13_ch), position = "stack") +
  theme_mms(
    plot_margin = margin(15, 20, 0, 10),
    grid=F, axis=F, 
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 3),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 3)
  ) +
  theme(
    legend.position = "none",
    #panel.background = element_rect(fill = NA),  # transparent
    #panel.ontop = TRUE
    axis.ticks.x = element_blank(), # Ajoute ça pour supprimer les graduations
    axis.line.x = element_blank(),   # Ajoute ça pour supprimer la ligne de l'axe
    axis.text.x = element_text(size = 12, margin=margin(t=0)),
    axis.title.y = element_textbox_simple(
      hjust = 0.5,
      halign = 0.5,
      r = unit(5, "pt"),
      orientation = "left-rotated",
      minwidth = unit(2, "in"),
      maxwidth = unit(5, "in"),
      padding = margin(6, 10, 6, 10),
      margin = margin(0, 0, 15, 0),
      fill = box_col,
      color = darken(mms_axis_tick_txt_color, 0.5),
      size =clabel_size
    )
  ) +
  scale_y_continuous(expand = c(0,0), 
                     breaks = NULL,
                     #breaks = seq(25, 100, 25),
                     labels = function(x) paste0(x, "%")) +
  scale_x_discrete(name = "", expand = c(0.1,0.1)
  ) +
  labs(
    subtitle = "In <b>the news from</b> ",
    y = "Switzerland"
  ) +
  geom_text(
    data = nic_df %>% filter(g13_ch != g132f$g13[1]),
    aes(y = share, group = g13_ch, 
        label = paste0(round(share,1), "%")),
    position = position_stack(vjust = 0.5),
    size = vlabel_size,
    color = "white",
    family = mms_base_family
  ) +
  scale_fill_manual(values = ni_cols)
  
 p_ni_1a
 
 p_ni_1b <- nih_df %>% 
   ggplot(aes(x = mig_4y)) +
   geom_col(aes(y = -share, fill = g13_home), position = "stack") +
   theme_mms(
     plot_margin = margin(0, 20, 5, 10),
     grid=F, axis=F, 
     mms_plot_title = mms_txtbox_plot.title(nrow_txt = 3),
     mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 3)
   ) +
   theme(
     legend.position = "none",
     panel.background = element_rect(fill = NA),  # transparent
     panel.ontop = TRUE,
     # On supprime TOUT ce qui est lié à l'axe X
     axis.text.x = element_blank(),
     axis.title.x = element_blank(),
     axis.ticks.x = element_blank(),
     axis.line.x = element_blank(),
    axis.title.y = element_textbox_simple(
      hjust = 0.5,
      halign = 0.5,
      r = unit(5, "pt"),
      orientation = "left-rotated",
      minwidth = unit(2, "in"),
      maxwidth = unit(5, "in"),
      padding = margin(6, 10, 6, 10),
      margin = margin(0, 0, 15, 0),
      fill = box_col,
      color = darken(mms_axis_tick_txt_color, 0.5),
      size =clabel_size
    )
   ) +
   scale_y_continuous(expand = c(0,0), name = "home country",
                      #position = "right",
                      breaks = NULL,
                      #breaks = seq(-25, -100, -25),
                      labels = function(x) paste0(abs(x), "%")) +
   scale_x_discrete(name = "", expand = c(0.1,0.1)
   ) +
   geom_text(
     data = nih_df %>% filter(g13_home != g132f$g13[1]),
     aes(y = -share, group = g13_home, 
         label = paste0(round(share,1), "%")),
     position = position_stack(vjust = 0.5),
     size = vlabel_size,
     color = "white",
     family = mms_base_family
   ) +
  scale_fill_manual(values = ni_cols)
 # scale_fill_manual(values = lighten(ni_cols, 0) %>% desaturate(0.5))
 
 
 p_ni_1b
 
 p_ni_1p <- (p_ni_1a / p_ni_1b) + 
   plot_layout(heights = c(1, 1), guides = 'collect') 

 p_ni_1p 
```

#### 2.   

```{r 2}
# exactly the same patchwork with nipc_df and niph_df
p_nip_2a <- nipc_df %>% 
  ggplot(aes(x = mig_4y)) +
  geom_col(aes(y = share, fill = g16_ch), position = "stack") +
  theme_mms(
    plot_margin = margin(15, 20, 0, 10),
    grid=F, axis=F, 
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 3),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 3)
  ) +
  theme(
    legend.position = "none",
    #panel.background = element_rect(fill = NA),  # transparent
    #panel.ontop = TRUE
    axis.ticks.x = element_blank(), # Ajoute ça pour supprimer les graduations
    axis.line.x = element_blank(),   # Ajoute ça pour supprimer la ligne de l'axe
    axis.text.x = element_text(size = 12, margin=margin(t=0)),
    axis.title.y.right = element_textbox_simple(
      hjust = 0.5,
      halign = 0.5,
      r = unit(5, "pt"),
      orientation = "right-rotated",
      minwidth = unit(2, "in"),
      maxwidth = unit(5, "in"),
      padding = margin(6, 10, 6, 10),
      margin = margin(0, 0, 15, 0),
      fill = box_col,
      color = darken(mms_axis_tick_txt_color, 0.5),
      size = clabel_size
    )
  ) +
  scale_y_continuous(expand = c(0,0), 
                     position = "right",
                     breaks = NULL,
                     #breaks = seq(25, 100, 25),
                     labels = function(x) paste0(x, "%")) +
  scale_x_discrete(name = "", expand = c(0.1,0.1)
  ) +
  labs(
    #title = "... and in the politics of ..."
    subtitle = "In<b> politics from</b> ",
    y = "Switzerland"
  ) +
  geom_text(
    #data = nipc_df %>% filter(g16_ch != g162f$g16[1]),
    aes(y = share, group = g16_ch, 
        label = paste0(round(share,1), "%")),
    position = position_stack(vjust = 0.5),
    size = vlabel_size,
    color = "white",
    family = mms_base_family
  ) +
  scale_fill_manual(values = ni_cols)
p_nip_2a


p_nip_2b <- niph_df %>% 
  ggplot(aes(x = mig_4y)) +
  geom_col(aes(y = -share, fill = g16_home), position = "stack") +
  theme_mms(
    plot_margin = margin(0, 20, 5, 10),
    grid=F, axis=F, 
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 3),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 3)
  ) +
  theme(
    legend.position = "none",
    panel.background = element_rect(fill = NA),  # transparent
    panel.ontop = TRUE,
    # On supprime TOUT ce qui est lié à l'axe X
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.line.x = element_blank(),
    axis.title.y.right = element_textbox_simple(
      hjust = 0.5,
      halign = 0.5,
      r = unit(5, "pt"),
      orientation = "right-rotated",
      minwidth = unit(2, "in"),
      maxwidth = unit(5, "in"),
      padding = margin(6, 10, 6, 10),
      margin = margin(0, 0, 15, 0),
      fill = box_col,
      color = darken(mms_axis_tick_txt_color, 0.5),
      size =clabel_size
    )
  ) +
  scale_y_continuous(expand = c(0,0), 
                     position = "right",
                     name = "home country",  
                     breaks = NULL,
                     #breaks = seq(-25, -100, -25),
                     labels = function(x) paste0(abs(x), "%")) +
  scale_x_discrete(name = "", expand = c(0.1,0.1)
  ) +
  geom_text(
    #data = niph_df %>% filter(g16_home != g162f$g16[1]),
    aes(y = -share, group = g16_home, 
        label = paste0(round(share,1), "%")),
    position = position_stack(vjust = 0.5),
    size = vlabel_size,
    color = "white",
    family = mms_base_family
  ) +
  scale_fill_manual(values = ni_cols)

p_nip_2b

p_pi_2p <- (p_nip_2a / p_nip_2b) + 
  plot_layout(heights = c(1, 1), guides = 'collect')
p_pi_2p

```


#### patch

```{r patch}

# plot_final <- p_ni_1a / p_ni_1b / p_nip_2a / p_nip_2b
# patchwork <- plot_final +
#   plot_layout(guides = 'collect')
# patchwork


plot_final <- (p_ni_1a / p_ni_1b) | (p_nip_2a / p_nip_2b)
patchwork <- plot_final +
  plot_layout(guides = 'collect') +
  plot_annotation(
    title = "As time of residence in Switzerland increases, interest in local news and politics grows while interest in the home country's declines",
    subtitle = str_c("Level of interest: ",
                    "<span style='color:", ni_cols[1], ";'><b>low</b></span>, ",
                    "<span style='color:", ni_cols[2], ";'><b>moderate</b></span> or ",
                    "<span style='color:", ni_cols[3], ";'><b>high</b></span>",
                     ", by migration year in 2024 survey"),
    theme = theme_mms(
      mms_plot_title = mms_txtbox_plot.title(nrow_txt = 3),
      mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 1)
    ))
    
patchwork


#p_ni_1p + p_pi_2p

mms_export_vector(
  plot = patchwork,
  filepath = here("Output", "charts", "N_newsInterest.svg"),
  bg_col = pw_bg_color
  )


```