---
title: "O Satisfaction of migrating to Switzerland"
author: "Duc-Quang Nguyen"
date: "2025-05-10"
output: html_document
---

```{r setup & load data, include=FALSE}
source("_helpers.R")
run_n_check <- T
```


```{r load}
# gender
c2t_A1 <- read_csv(here("Data", "code2txt", "NCCR MMS Codes A1.csv"))
# education
c2t_D1 <- read_csv(here("Data", "code2txt", "NCCR MMS Codes D1.csv"))
# pays 
c2t_B1 <- read_csv(here("Data", "code2txt", "NCCR_MMS_codes - B1.csv"))

c1_codes <- tibble(
 C1 = c(1, 2, 3, 4, 5, 6, 7),
 nat = c("yes", "yes", "no", "no", "don't know", "yes", "yes")
)

h6 <- mms_load_data(F) %>% 
  select(H6_5)

h62f <- tibble(
 H6_5 = 0:10,
 h6 = c(rep("low", 3),  rep("moderate", 5), rep("high", 3))
) %>% 
  mutate(
    h6 = factor(h6, levels = c("low", "moderate", "high"))
  )

edu2f <- tibble(
  groupe_edu = c("Secondaire I", "Secondaire II", "Tertiaire"),
  edu = c("Secondary I & II", "Secondary I & II", "Tertiary")
)

data_all <- bind_cols(mms_df, h6)  %>% 
  left_join(h62f) %>%
 # hack in 2024 C1 column is named c1
  mutate(
    C1 = ifelse(year == 2024, c1, C1)
  ) %>% 
  left_join(
    c1_codes, by = "C1"
  ) %>% 
  left_join(c2t_A1) %>% 
  left_join(c2t_B1) %>% 
  left_join(c2t_D1) %>% 
  left_join(edu2f) %>%
  left_join(pays2col) 

o_df <- data_all %>% 
  select(year:color)


```

### Wrangle & check

```{r wrangle & check}
sa_df <- o_df %>% 
  filter(!is.na(h6)) %>% 
  filter(!is.na(year)) %>% 
  group_by(year, h6) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>% 
  group_by(year) %>% 
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100
  ) %>% 
  ungroup() 

if(run_n_check) {
  sa_df %>% 
    select(year, h6, share, n_y) %>%
    pivot_wider(
      names_from = h6,
      values_from = share
    )
}

sa_s_df <- o_df %>% 
  filter(!is.na(h6)) %>% 
  filter(!is.na(year)) %>% 
  filter(!is.na(sexe)) %>% 
  filter(year == 2024) %>%
  group_by(sexe, h6) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>% 
  group_by(sexe) %>% 
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100
  ) %>% 
  ungroup()

if(run_n_check) {
  sa_s_df %>% 
    select(sexe, h6, share, n_y) %>%
    pivot_wider(
      names_from = h6,
      values_from = share
    )
}

sa_n_df <- o_df %>% 
  filter(!is.na(h6)) %>% 
  filter(!is.na(year)) %>% 
  filter(!is.na(nat)) %>% 
  filter(year == 2024) %>%
  group_by(nat, h6) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>% 
  group_by(nat) %>% 
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100
  ) %>% 
  ungroup() %>% 
  mutate(
    nat = factor(nat, levels = rev(c("yes", "don't know", "no")))
  ) 

if(run_n_check) {
  sa_n_df %>% 
    select(nat, h6, share, n_y) %>%
    pivot_wider(
      names_from = h6,
      values_from = share
    )
}

sa_e_df <- o_df %>% 
  filter(!is.na(h6)) %>% 
  filter(!is.na(year)) %>% 
  filter(!is.na(edu)) %>% 
  filter(year == 2024) %>%
  group_by(edu, h6) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>% 
  group_by(edu) %>% 
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100
  ) %>% 
  ungroup()
  

if(run_n_check) {
  sa_e_df %>% 
    select(edu, h6, share, n_y) %>%
    pivot_wider(
      names_from = h6,
      values_from = share
    )
}


sa_ec_df <- o_df %>% 
  filter(!is.na(h6)) %>% 
  filter(!is.na(year)) %>% 
  filter(!is.na(edu)) %>% 
  filter(!is.na(country)) %>% 
  filter(year == 2024) %>%
  group_by(edu, country, h6) %>% 
  reframe(
    n = n(),
    weight = sum(weight, na.rm = TRUE)
  ) %>% 
  group_by(country, edu) %>% 
  mutate(
    n_y = sum(n, na.rm = TRUE),
    share = weight/sum(weight, na.rm = TRUE)*100
  ) %>% 
  ungroup() %>% 
  filter(country != "Other countries") %>% 
  arrange(country, edu) %>% 
  filter(h6 == h62f$h6[10]) 


if(run_n_check) {
  sa_ec_df %>% 
    select(country, edu, share, n_y) %>%
    pivot_wider(
      names_from = edu,
      values_from = c(share, n_y)
    )
}

```


### VIZ

#### 1. main  chart

```{r 1}

sa_cols <- nccr_bi_colors[c(3,3,4)]
sa_cols[1] <- lighten(sa_cols[1], 0.4) %>% desaturate(0.5)

p_sa_1 <- sa_df %>%
  ggplot(aes(x = year, y = share)) +
  geom_area(aes(fill = h6), linewidth = 1, 
            color = "white", 
            position = position_stack(reverse = TRUE)) +
  geom_text(
    data = tibble(
      year = c(2020, 2020),
      share_w = c(10, 56),
      label = h62f$h6[c(5,10)]
    ),
    aes(x = year, y = share_w, label = label),
    color = "white",
    size = 5,
    family = mms_base_family
    #fontface = "bold"
  ) +
 theme_mms(
    grid="XY", axis="xy", 
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 3),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 2)
  ) +
  theme(
    legend.position = "none",
    panel.background = element_rect(fill = NA),  # transparent
    panel.ontop = TRUE
  ) +
  scale_y_continuous(
    name = "",
    expand = c(0, 0),
    breaks = seq(25, 100, by = 25),
    labels = function(x) paste0(x, "%")
  ) +
  scale_x_continuous(expand = c(0, 0), name = "") +
  scale_fill_manual(values = sa_cols) +
  labs(
    title = str_c("Four out of five people are satisfied with their decision to migrate to Switzerland, with little change over time"),
    subtitle = str_c("Level of satisfaction of moving to Switzerland, by survey year: ",
                    "<span style='color:", sa_cols[1], ";'><b>low</b></span>, ",
                   "<span style='color:", sa_cols[2], ";'><b>moderate</b></span> or ",
                   "<span style='color:", sa_cols[3], ";'><b>high</b></span>")
  )

p_sa_1  
```

#### 2.   

```{r 2 by sex}

sa_s_df %<>% 
  select(sexe, h6, share, n_y) %>% 
  # create coords for donut chart https://r-graph-gallery.com/128-ring-or-donut-plot.html
  group_by(sexe) %>% 
  mutate(
    ymax = cumsum(share),
    ymin = c(0, head(ymax, n=-1)),
    # Compute label position
    label_pos = (ymax + ymin) / 2,
    # Compute a good label
    label = paste0(round(share, num_n_dect), "%")
  ) %>%
  ungroup()

gender_labels <-tibble(
  sexe = distinct(sa_s_df, sexe) %>% deframe(),
  label = c("women", "men"),
  color = nccr_bi_colors[c(12,2)]
)

p_sa_2 <- sa_s_df %>%
 ggplot(
   aes(ymax=ymax, ymin=ymin, xmax=4.5, xmin=3, fill=h6)) +
  geom_rect(color = "white") +
  geom_label(
    data = sa_s_df %>% filter(h6 !=  h62f$h6[1]),
    x=3.7,
    aes(y=label_pos, label=label, group = rev(h6)),
    color = "white",
    size=4,
    fill = NA, label.size = 0,
    family = mms_base_family) +
  facet_wrap(~sexe, ncol =2) +
  coord_polar(theta="y") + # Try to remove that to understand how the chart is built initially
  theme_mms(
    grid=F, 
    axis=F,
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 4),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 4)
  ) +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    legend.position = "none",
    panel.spacing = unit(0, "pt"),  # reduce space between facets
    strip.text = element_blank(),
    strip.background = element_blank()
  ) +
  scale_fill_manual(values = sa_cols) +
  scale_color_identity() +
  scale_y_continuous(name = "", expand = c(0, 0)) +
  scale_x_continuous(name = "", expand = c(0, 0), limits = c(2, 4.5)) +
  geom_text(
    data = gender_labels,
    aes(x = 2, y = 0, label = label, color = color), # Position text at the center
    inherit.aes = FALSE, # IMPORTANT: Prevents inheriting aesthetics from ggplot()
    size = 4,
    family = mms_base_family, fontface = "bold"
  ) +
  labs(
    title = str_c("Women are less satisfied than men with their move to Switzerland"),
    subtitle = str_c("Level of satisfaction of moving to Switzerland, in 2024 by gender: ",
                    "<span style='color:", sa_cols[1], ";'><b>low</b></span>, ",
                   "<span style='color:", sa_cols[2], ";'><b>moderate</b></span> or ",
                   "<span style='color:", sa_cols[3], ";'><b>high</b></span>")
  )

p_sa_2

```

#### 3.

```{r 3}
sa_n_labels <- sa_n_df %>% 
  select(nat) %>% distinct() %>% 
  mutate(
    share = 0
  )

# dodged bar chart by naturalisation will
p_sa_3 <- sa_n_df %>%
  ggplot(aes(x = share, y = nat, fill = h6)) +
  # geom_bar(stat = "identity", position = position_dodge2(preserve = "single")) +
  geom_bar(stat = "identity", position = "stack") +
  theme_mms(
    grid=F, 
    axis=F,
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 4),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 4)
  ) +
  theme(
    axis.text.x = element_blank(),
    legend.position = "none",
    axis.text.y = element_blank()
  ) +
  scale_y_discrete(name = "", expand = c(0, 0)) +
  scale_x_continuous(name = "", expand = c(0, 0)) +
  scale_fill_manual(values = sa_cols) +
  geom_text(
    data = sa_n_df %>% filter(h6 != h62f$h6[1]),
    aes(label = paste0(round(share, num_n_dect), "%")),
    position = position_stack(vjust = 0.5),
    vjust = 3,
    color = "white",
    size = 3,
    family = mms_base_family
  ) +
  scale_color_identity() +
  geom_text(
    data = sa_n_labels,
    aes(x = share, y = nat, label = nat), # Position text at the center
    inherit.aes = FALSE, # IMPORTANT: Prevents inheriting aesthetics from ggplot()
    size = 4,
    color = "white",
    vjust = -2,
    hjust = 0,
    nudge_x = 2,
    family = mms_base_family, fontface = "bold"
  ) +
  labs(
    title = str_c("People intending to naturalize are more satisfied with their move to Switzerland"),
    subtitle = str_c("Level of satisfaction of moving to Switzerland, in 2024 by intent to naturalize: ",
                   "<span style='color:", sa_cols[3],
                    ";'><b>high</b></span>, ",
                   "<span style='color:", sa_cols[2], ";'><b>moderate</b></span> or ",
                   "<span style='color:", sa_cols[1], ";'><b>low</b></span>")
  )

  
p_sa_3

```

#### 4.

```{r 4}
# same as above by edu 
sa_e_labels <- sa_e_df %>% 
  select(edu) %>% distinct() %>% 
  mutate(
    share = 0
  )
# dodged bar chart by naturalisation will
p_sa_4 <- sa_e_df %>%
  ggplot(aes(x = share, y = edu, fill = h6
             )) +
  # geom_bar(stat = "identity", position = position_dodge2(preserve = "single")) +
  geom_bar(stat = "identity", position = "stack") +
  theme_mms(
    grid=F, 
    axis=F,
    mms_plot_title = mms_txtbox_plot.title(nrow_txt = 4),
    mms_plot_subtitle = mms_txtbox_plot.subtitle(nrow_txt = 4)
  ) +
  theme(
    axis.text.x = element_blank(),
    legend.position = "none",
    axis.text.y = element_blank()
  ) +
  scale_y_discrete(name = "", expand = c(0, 0)) +
  scale_x_continuous(name = "", expand = c(0, 0)) +
  scale_fill_manual(values = sa_cols) +
  geom_text(
    data = sa_e_df %>% filter(h6 != h62f$h6[1]),
    aes(label = paste0(round(share, num_n_dect), "%")),
    position = position_stack(vjust = 0.5),
    vjust = 6,
    color = "white",
    size = 3,
    family = mms_base_family
  ) +
  scale_color_identity() +
  geom_text(
    data = sa_e_labels,
    aes(x = share, y = edu, label = edu), # Position text at the center
    inherit.aes = FALSE, # IMPORTANT: Prevents inheriting aesthetics from ggplot()
    size = 4,
    color = "white",
    vjust = -3.2,
    hjust = 0,
    nudge_x = 3,
    family = mms_base_family, fontface = "bold"
  ) +
  labs(
    title = str_c("People with higher education are more satisfied with their move to Switzerland"),
    subtitle = str_c("Level of satisfaction of moving to Switzerland, in 2024 by education level: ",
                   "<span style='color:", sa_cols[3],
                    ";'><b>high</b></span>, ",
                   "<span style='color:", sa_cols[2], ";'><b>moderate</b></span> or ",
                   "<span style='color:", sa_cols[1], ";'><b>low</b></span>")  
  )

p_sa_4
```

#### 5.

```{r 5}
# a dot plot range chart by country & edu ?? 

sa_ec_df %>% 
  ggplot(aes(x = share, y = country, color = edu)) 


```

#### patch

```{r patch}

# mms_export_vector(
#   plot = patchwork,
#   filepath = #here("Output", "charts", ""),
#   bg_col = pw_bg_color
#   )


```